/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.senac.integrador.escola.modelos.telas.tela_professor;

import br.com.senac.integrador.escola.modelos.telas.tela_aluno.*;
import br.com.senac.integrador.escola.modelos.auxiliares.LoginSessionAlunos;
import br.com.senac.integrador.escola.modelos.auxiliares.LoginSessionProfessores;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jonathan
 */
public class page_turmas extends javax.swing.JInternalFrame {

    DefaultTableModel model_disciplina;
    DefaultTableModel model_turma;
    DefaultTableModel model_frequencia;
    
    /**
     * Creates new form Inicio
     */
    public page_turmas() throws SQLException {
        initComponents();
        
        model_disciplina = (DefaultTableModel) table_disciplina.getModel();  
        model_turma = (DefaultTableModel) table_turma.getModel();  
        model_frequencia = (DefaultTableModel) table_frequencia.getModel();  
              
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
        fillcombos();
        getTurma();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tab_inicio = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        table_disciplina = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        table_turma = new javax.swing.JTable();
        combo_trimestre = new javax.swing.JComboBox<>();
        combo_turma = new javax.swing.JComboBox<>();
        combo_curso = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        table_desempenho = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_frequencia = new javax.swing.JTable();
        combo_trimestre_Freq = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(590, 480));

        tab_inicio.setBackground(new java.awt.Color(67, 148, 222));
        tab_inicio.setPreferredSize(new java.awt.Dimension(590, 480));

        table_disciplina.setFont(new java.awt.Font("Segoe UI Semibold", 1, 10)); // NOI18N
        table_disciplina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Disciplina", "Tipo", "Data", "Nota"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_disciplina.setToolTipText("");
        table_disciplina.setFocusable(false);
        table_disciplina.setGridColor(new java.awt.Color(0, 0, 0));
        table_disciplina.setIntercellSpacing(new java.awt.Dimension(0, 0));
        table_disciplina.setPreferredSize(new java.awt.Dimension(278, 287));
        table_disciplina.setRowHeight(20);
        table_disciplina.setSelectionBackground(new java.awt.Color(232, 180, 88));
        table_disciplina.setShowGrid(true);
        table_disciplina.setShowHorizontalLines(false);
        table_disciplina.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(table_disciplina);
        table_disciplina.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        table_disciplina.getTableHeader().setOpaque(false);
        table_disciplina.setRowHeight(20);
        if (table_disciplina.getColumnModel().getColumnCount() > 0) {
            table_disciplina.getColumnModel().getColumn(0).setPreferredWidth(60);
            table_disciplina.getColumnModel().getColumn(2).setPreferredWidth(30);
            table_disciplina.getColumnModel().getColumn(3).setPreferredWidth(60);
        }

        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        table_turma.setFont(new java.awt.Font("Segoe UI Semibold", 1, 10)); // NOI18N
        table_turma.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Estudante", "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_turma.setToolTipText("");
        table_turma.setFocusable(false);
        table_turma.setGridColor(new java.awt.Color(0, 0, 0));
        table_turma.setIntercellSpacing(new java.awt.Dimension(0, 0));
        table_turma.setPreferredSize(new java.awt.Dimension(278, 287));
        table_turma.setRowHeight(18);
        table_turma.setSelectionBackground(new java.awt.Color(232, 180, 88));
        table_turma.setShowGrid(true);
        table_turma.setShowHorizontalLines(false);
        table_turma.getTableHeader().setReorderingAllowed(false);
        table_turma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_turmaMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(table_turma);
        table_turma.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        table_turma.getTableHeader().setOpaque(false);
        table_turma.setRowHeight(18);

        combo_trimestre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1º Tri", "2º Tri", "3º Tri"}));
        combo_trimestre.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_trimestreItemStateChanged(evt);
            }
        });

        combo_turma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));
        combo_turma.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_turmaItemStateChanged(evt);
            }
        });
        combo_turma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_turmaActionPerformed(evt);
            }
        });

        combo_curso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        combo_curso.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_cursoItemStateChanged(evt);
            }
        });
        combo_curso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_cursoActionPerformed(evt);
            }
        });

        jButton2.setText("Editar Notas");

        jScrollPane6.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        table_desempenho.setFont(new java.awt.Font("Segoe UI Semibold", 1, 10)); // NOI18N
        table_desempenho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Biologia", "", "", "", "", "", "", "", ""}
            },
            new String [] {
                "", "1º Tri", "F", "2º Tri", "F", "3º Tri", "F", "Avaliação Final", "F"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_desempenho.setToolTipText("");
        table_desempenho.setFocusable(false);
        table_desempenho.setGridColor(new java.awt.Color(0, 0, 0));
        table_desempenho.setIntercellSpacing(new java.awt.Dimension(0, 0));
        table_desempenho.setPreferredSize(new java.awt.Dimension(278, 287));
        table_desempenho.setRowHeight(18);
        table_desempenho.setSelectionBackground(new java.awt.Color(232, 180, 88));
        table_desempenho.setShowGrid(true);
        table_desempenho.setShowHorizontalLines(false);
        table_desempenho.getTableHeader().setReorderingAllowed(false);
        table_desempenho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_desempenhoMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(table_desempenho);

        table_frequencia.setFont(new java.awt.Font("Segoe UI Semibold", 1, 10)); // NOI18N
        table_frequencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Disciplina", "Data"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_frequencia.setFocusable(false);
        table_frequencia.setGridColor(new java.awt.Color(0, 0, 0));
        table_frequencia.setIntercellSpacing(new java.awt.Dimension(0, 0));
        table_frequencia.setRowHeight(18);
        table_frequencia.setSelectionBackground(new java.awt.Color(232, 180, 88));
        table_frequencia.setShowGrid(true);
        table_frequencia.setShowHorizontalLines(false);
        jScrollPane2.setViewportView(table_frequencia);

        combo_trimestre_Freq.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1º Tri", "2º Tri", "3º Tri"}));
        combo_trimestre_Freq.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_trimestre_FreqItemStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Boletim");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Frequência");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Alunos");

        jButton3.setText("Editar Frequência");

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Notas (Aluno Selecionado)");

        javax.swing.GroupLayout tab_inicioLayout = new javax.swing.GroupLayout(tab_inicio);
        tab_inicio.setLayout(tab_inicioLayout);
        tab_inicioLayout.setHorizontalGroup(
            tab_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_inicioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tab_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tab_inicioLayout.createSequentialGroup()
                        .addComponent(combo_trimestre, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addComponent(jScrollPane6)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tab_inicioLayout.createSequentialGroup()
                        .addGroup(tab_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tab_inicioLayout.createSequentialGroup()
                                .addComponent(combo_curso, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(combo_turma, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(combo_trimestre_Freq, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(tab_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab_inicioLayout.createSequentialGroup()
                    .addContainerGap(294, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        tab_inicioLayout.setVerticalGroup(
            tab_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab_inicioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tab_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tab_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(combo_turma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(combo_curso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tab_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(combo_trimestre_Freq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(tab_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_trimestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(tab_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tab_inicioLayout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(226, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab_inicio, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab_inicio, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void table_turmaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_turmaMouseClicked
        if(table_turma.getSelectedRow() == 0) 
        {
            try {
                fillDisciplina(1, combo_trimestre.getSelectedIndex() + 1);
                fillFrequencia(1, combo_trimestre_Freq.getSelectedIndex() + 1);
            } catch (SQLException ex) {
                Logger.getLogger(page_turmas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        else 
        {
            try {
                fillDisciplina((int) table_turma.getValueAt(table_turma.getSelectedRow(), 0), combo_trimestre.getSelectedIndex() + 1);
                fillFrequencia((int) table_turma.getValueAt(table_turma.getSelectedRow(), 0), combo_trimestre_Freq.getSelectedIndex() + 1);
            } catch (SQLException ex) {
                Logger.getLogger(page_turmas.class.getName()).log(Level.SEVERE, null, ex);
            }           
        }
    }//GEN-LAST:event_table_turmaMouseClicked

    private void combo_trimestreItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_trimestreItemStateChanged
        try {
            fillDisciplina((int) table_turma.getValueAt(table_turma.getSelectedRow(), 0), combo_trimestre.getSelectedIndex() + 1);
        } catch (SQLException ex) {
            Logger.getLogger(page_turmas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_combo_trimestreItemStateChanged

    private void combo_turmaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_turmaItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_turmaItemStateChanged

    private void combo_turmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_turmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_turmaActionPerformed

    private void combo_cursoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_cursoItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_cursoItemStateChanged

    private void combo_cursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_cursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_cursoActionPerformed

    private void table_desempenhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_desempenhoMouseClicked
        if(table_desempenho.getSelectedRow() == 0 )
        {
            try {
                fillDisciplina(1, combo_trimestre.getSelectedIndex() + 1);
            } catch (SQLException ex) {
                Logger.getLogger(page_desempenho.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        else
        {
            try {
                fillDisciplina((int) table_turma.getValueAt(table_turma.getSelectedRow(), 0), combo_trimestre.getSelectedIndex() + 1);
            } catch (SQLException ex) {
                Logger.getLogger(page_desempenho.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_table_desempenhoMouseClicked

    private void combo_trimestre_FreqItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_trimestre_FreqItemStateChanged
        try {
            fillFrequencia((int) table_turma.getValueAt(table_turma.getSelectedRow(), 0), combo_trimestre_Freq.getSelectedIndex() + 1);
        } catch (SQLException ex) {
            Logger.getLogger(page_frequencia.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_combo_trimestre_FreqItemStateChanged
    
    private void fillFrequencia(int idEstudante, int trimestre) throws SQLException 
    {
        connection = createConnection();
        Statement statement = connection.createStatement();
        
        ResultSet faltas = statement.executeQuery("SELECT * from faltas where idEstudante = " + idEstudante + " and disciplinaFalta = '" + LoginSessionProfessores.disciplina + "' and trimestre = " + trimestre);

        model_frequencia.setRowCount(0);
        
        while(faltas.next())
        {
            String disciplina = LoginSessionProfessores.disciplina;
            String data = faltas.getString("dataFalta");
            
            Object dadosFalta[] = {data, disciplina};  
            
            model_frequencia.addRow(dadosFalta);
        } 
    }    
    
    private static boolean isSQLSet = false;
    private static Connection connection;
    
    private static Connection createConnection() throws SQLException {
        if(isSQLSet) {
            return connection;
        }
        //String username = JOptionPane.showInputDialog("Insira o usuário do banco de dados.");
        //String password = JOptionPane.showInputDialog("Insira a senha do banco de dados.");
        
        String username = "root";
        String password = "inserida";
        
        String url = "jdbc:mysql://localhost/appescola";
        isSQLSet = true;
        connection = DriverManager.getConnection(url, username, password);
        return connection;
    }
    
    private void fillcombos() {
        try {
            connection = createConnection();
            Statement st_combo = connection.createStatement();
            Statement st_comboTurma = connection.createStatement();
            
            ResultSet rs_combo = st_combo.executeQuery("SELECT escolaridade FROM turma");
            ResultSet rs_turma = st_comboTurma.executeQuery("SELECT idTurma FROM turma");
            
            while(rs_turma.next()) {
                combo_turma.addItem(rs_turma.getString("idTurma"));
            }
            
            while(rs_combo.next()) {
                combo_curso.addItem(rs_combo.getString("escolaridade"));
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(page_turmas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void getTurma() throws SQLException 
    {
        connection = createConnection();
        Statement st_alunos = connection.createStatement();
           
        ResultSet rs_alunos = st_alunos.executeQuery("SELECT nome, idEstudante FROM estudante WHERE idTurma = " + combo_turma.getSelectedItem() + " AND escolaridade = '" + combo_curso.getSelectedItem() + "'");        
        while (rs_alunos.next()) {
            Object nome[] = {rs_alunos.getString("idEstudante"), rs_alunos.getString("nome")};
            model_turma.addRow(nome);
        }
    }
    
    private void fillDisciplina(int idEstudante, int trimestre) throws SQLException 
    {
        connection = createConnection();
        Statement statement = connection.createStatement();
        
        ResultSet notas = statement.executeQuery("SELECT * from nota where idEstudante = " + idEstudante + " and disciplinaNota = '" + LoginSessionProfessores.disciplina + "' and trimestre = " + trimestre);

        model_disciplina.setRowCount(0);
        
        while(notas.next())
        {
            String disciplina = notas.getString("disciplinaNota");
            String tipo = notas.getString("tipoNota");
            String data = notas.getString("dataNota");
            double nota = notas.getDouble("nota");
            
            Object dadosNota[] = {disciplina, tipo, data, nota};  
            
            model_disciplina.addRow(dadosNota);
        } 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo_curso;
    private javax.swing.JComboBox<String> combo_trimestre;
    private javax.swing.JComboBox<String> combo_trimestre_Freq;
    private javax.swing.JComboBox<String> combo_turma;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPanel tab_inicio;
    private javax.swing.JTable table_desempenho;
    private javax.swing.JTable table_disciplina;
    private javax.swing.JTable table_frequencia;
    private javax.swing.JTable table_turma;
    // End of variables declaration//GEN-END:variables
}
