/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.senac.integrador.escola.modelos.telas.tela_professor;

import br.com.senac.integrador.escola.modelos.telas.tela_aluno.*;
import br.com.senac.integrador.escola.modelos.auxiliares.LoginSessionAlunos;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.Month;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Jonathan
 */
public class page_contato extends javax.swing.JInternalFrame {
    /**
     * Creates new form Inicio
     */
    public page_contato() {
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tab_inicio = new javax.swing.JPanel();
        label_mensagem = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        field_descricao = new javax.swing.JTextArea();
        button_enviar_solicitacao = new javax.swing.JButton();
        label_charCounter = new javax.swing.JLabel();
        charCount = new javax.swing.JLabel();
        label_tipoOcorrencia7 = new javax.swing.JLabel();
        label_tipoOcorrencia8 = new javax.swing.JLabel();
        label_tipoOcorrencia9 = new javax.swing.JLabel();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(590, 480));

        tab_inicio.setBackground(new java.awt.Color(67, 148, 222));
        tab_inicio.setPreferredSize(new java.awt.Dimension(590, 480));

        label_mensagem.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        label_mensagem.setForeground(new java.awt.Color(255, 255, 255));
        label_mensagem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_mensagem.setText("Mensagem para a coordenação:");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        field_descricao.setColumns(20);
        field_descricao.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        field_descricao.setLineWrap(true);
        field_descricao.setRows(5);
        field_descricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                field_descricaoKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(field_descricao);

        button_enviar_solicitacao.setFont(new java.awt.Font("Segoe UI Semibold", 1, 11)); // NOI18N
        button_enviar_solicitacao.setText("Enviar");
        button_enviar_solicitacao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_enviar_solicitacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_enviar_solicitacaoMouseClicked(evt);
            }
        });

        label_charCounter.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        label_charCounter.setForeground(new java.awt.Color(255, 255, 255));
        label_charCounter.setText("Caracteres:");

        charCount.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        charCount.setForeground(new java.awt.Color(255, 255, 255));

        label_tipoOcorrencia7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        label_tipoOcorrencia7.setForeground(new java.awt.Color(255, 255, 255));
        label_tipoOcorrencia7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_tipoOcorrencia7.setText("Telefone: xx x xxxx-xxxx");

        label_tipoOcorrencia8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        label_tipoOcorrencia8.setForeground(new java.awt.Color(255, 255, 255));
        label_tipoOcorrencia8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_tipoOcorrencia8.setText("Email: xx x xxxx-xxxx");

        label_tipoOcorrencia9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        label_tipoOcorrencia9.setForeground(new java.awt.Color(255, 255, 255));
        label_tipoOcorrencia9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_tipoOcorrencia9.setText("Email: colegio@gmail.com");

        javax.swing.GroupLayout tab_inicioLayout = new javax.swing.GroupLayout(tab_inicio);
        tab_inicio.setLayout(tab_inicioLayout);
        tab_inicioLayout.setHorizontalGroup(
            tab_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_inicioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tab_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                    .addGroup(tab_inicioLayout.createSequentialGroup()
                        .addComponent(button_enviar_solicitacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label_charCounter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(charCount, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tab_inicioLayout.createSequentialGroup()
                        .addGroup(tab_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_mensagem)
                            .addComponent(label_tipoOcorrencia7)
                            .addComponent(label_tipoOcorrencia8)
                            .addComponent(label_tipoOcorrencia9))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tab_inicioLayout.setVerticalGroup(
            tab_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_inicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_mensagem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tab_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tab_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label_charCounter)
                        .addComponent(charCount))
                    .addComponent(button_enviar_solicitacao))
                .addGap(61, 61, 61)
                .addComponent(label_tipoOcorrencia7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_tipoOcorrencia9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_tipoOcorrencia8)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab_inicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab_inicio, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

 
    private static boolean isSQLSet = false;
    private static Connection connection;
    
    private static Connection createConnection() throws SQLException {
        if(isSQLSet) {
            return connection;
        }
        //String username = JOptionPane.showInputDialog("Insira o usuário do banco de dados.");
        //String password = JOptionPane.showInputDialog("Insira a senha do banco de dados.");
        
        String username = "root";
        String password = "inserida";
        
        String url = "jdbc:mysql://localhost/appescola";
        isSQLSet = true;
        connection = DriverManager.getConnection(url, username, password);
        return connection;
    } 
    
    private void field_descricaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_field_descricaoKeyTyped
        String charNum = String.valueOf(field_descricao.getText().length());

        charCount.setText(charNum);

        if (field_descricao.getText().length() > 512)
        {
            charCount.setForeground(Color.red);
        }

        else
        {
            charCount.setForeground(Color.white);
        }
    }//GEN-LAST:event_field_descricaoKeyTyped

    private void button_enviar_solicitacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_enviar_solicitacaoMouseClicked
        try {
            submitSolicitacao(LoginSessionAlunos.idEstudante);
        } catch (SQLException ex) {
            Logger.getLogger(page_ocorrencias.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_button_enviar_solicitacaoMouseClicked

    private void submitSolicitacao(int idEstudante) throws SQLException {
        connection = createConnection();
        Statement enviar = connection.createStatement();
        
        boolean mostrar_nome;
        
        LocalDate date = LocalDate.now();
 
	Date currentDate = new Date();		
	SimpleDateFormat formatter = new SimpleDateFormat("kk:mm");		
	String currenttime = formatter.format(currentDate);
        
        enviar.executeUpdate("INSERT INTO solicitacao (dataSolicitacao, horaSolicitacao, idEstudante, descricao) VALUES('" 
            + date
            + "', '" 
            + currenttime 
            + "', "
            + idEstudante 
            + ", '"
            + field_descricao.getText()
            + "');"
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_enviar_solicitacao;
    private javax.swing.JLabel charCount;
    private javax.swing.JTextArea field_descricao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_charCounter;
    private javax.swing.JLabel label_mensagem;
    private javax.swing.JLabel label_tipoOcorrencia7;
    private javax.swing.JLabel label_tipoOcorrencia8;
    private javax.swing.JLabel label_tipoOcorrencia9;
    private javax.swing.JPanel tab_inicio;
    // End of variables declaration//GEN-END:variables
}
