/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.senac.integrador.escola.modelos.telas.tela_professor;

import br.com.senac.integrador.escola.modelos.telas.tela_aluno.*;
import br.com.senac.integrador.escola.modelos.auxiliares.LoginSessionAlunos;
import br.com.senac.integrador.escola.modelos.auxiliares.Logout;
import br.com.senac.integrador.escola.modelos.auxiliares.MySQL_Connection;
import br.com.senac.integrador.escola.modelos.auxiliares.SQLManager;
import br.com.senac.integrador.escola.login.Main_Login;
import br.com.senac.integrador.escola.modelos.auxiliares.LoginSessionProfessores;
import java.awt.Color;
import java.awt.Component;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.Border;

/**
 *
 * @author Jonathan
 */
public class Tela_Professor extends javax.swing.JFrame {
    
    /**
     * Creates new form Tela_Aluno
     */
    public Tela_Professor() throws SQLException {
        initComponents();
        open_page(inicio);
        getTopBarData(LoginSessionProfessores.idPessoa, LoginSessionProfessores.idProfessor);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navbar = new javax.swing.JPanel();
        nav_inicio = new javax.swing.JPanel();
        label_inicio = new javax.swing.JLabel();
        nav_turmas = new javax.swing.JPanel();
        label_turmas = new javax.swing.JLabel();
        nav_ocorrencias = new javax.swing.JPanel();
        label_ocorrencias = new javax.swing.JLabel();
        nav_perfil = new javax.swing.JPanel();
        label_perfil = new javax.swing.JLabel();
        nav_contato = new javax.swing.JPanel();
        label_contato = new javax.swing.JLabel();
        nav_diario = new javax.swing.JPanel();
        label_diario = new javax.swing.JLabel();
        renderer = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        topBar_perfil = new javax.swing.JLabel();
        topBar_nome = new javax.swing.JLabel();
        button_close = new javax.swing.JLabel();
        button_logout = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        navbar.setBackground(new java.awt.Color(54, 164, 255));

        nav_inicio.setBackground(new java.awt.Color(54, 164, 255));
        nav_inicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nav_inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nav_inicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nav_inicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nav_inicioMouseExited(evt);
            }
        });

        label_inicio.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        label_inicio.setForeground(new java.awt.Color(255, 255, 255));
        label_inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/integrador/escola/modelos/telas/tela_aluno/images/icon_inicio.png"))); // NOI18N
        label_inicio.setText("Início");

        javax.swing.GroupLayout nav_inicioLayout = new javax.swing.GroupLayout(nav_inicio);
        nav_inicio.setLayout(nav_inicioLayout);
        nav_inicioLayout.setHorizontalGroup(
            nav_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nav_inicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        nav_inicioLayout.setVerticalGroup(
            nav_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nav_inicioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label_inicio)
                .addContainerGap())
        );

        nav_turmas.setBackground(new java.awt.Color(54, 164, 255));
        nav_turmas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nav_turmas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nav_turmasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nav_turmasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nav_turmasMouseExited(evt);
            }
        });

        label_turmas.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        label_turmas.setForeground(new java.awt.Color(255, 255, 255));
        label_turmas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/integrador/escola/modelos/telas/tela_aluno/images/icon_turma.png"))); // NOI18N
        label_turmas.setText("Turmas");

        javax.swing.GroupLayout nav_turmasLayout = new javax.swing.GroupLayout(nav_turmas);
        nav_turmas.setLayout(nav_turmasLayout);
        nav_turmasLayout.setHorizontalGroup(
            nav_turmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nav_turmasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_turmas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );
        nav_turmasLayout.setVerticalGroup(
            nav_turmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nav_turmasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_turmas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        nav_ocorrencias.setBackground(new java.awt.Color(54, 164, 255));
        nav_ocorrencias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nav_ocorrencias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nav_ocorrenciasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nav_ocorrenciasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nav_ocorrenciasMouseExited(evt);
            }
        });

        label_ocorrencias.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        label_ocorrencias.setForeground(new java.awt.Color(255, 255, 255));
        label_ocorrencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/integrador/escola/modelos/telas/tela_aluno/images/icon_ocorrencias.png"))); // NOI18N
        label_ocorrencias.setText("Ocorrências");

        javax.swing.GroupLayout nav_ocorrenciasLayout = new javax.swing.GroupLayout(nav_ocorrencias);
        nav_ocorrencias.setLayout(nav_ocorrenciasLayout);
        nav_ocorrenciasLayout.setHorizontalGroup(
            nav_ocorrenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nav_ocorrenciasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_ocorrencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        nav_ocorrenciasLayout.setVerticalGroup(
            nav_ocorrenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nav_ocorrenciasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_ocorrencias)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        nav_perfil.setBackground(new java.awt.Color(54, 164, 255));
        nav_perfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nav_perfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nav_perfilMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nav_perfilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nav_perfilMouseExited(evt);
            }
        });

        label_perfil.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        label_perfil.setForeground(new java.awt.Color(255, 255, 255));
        label_perfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/integrador/escola/modelos/telas/tela_aluno/images/icon_perfil.png"))); // NOI18N
        label_perfil.setText("Perfil");

        javax.swing.GroupLayout nav_perfilLayout = new javax.swing.GroupLayout(nav_perfil);
        nav_perfil.setLayout(nav_perfilLayout);
        nav_perfilLayout.setHorizontalGroup(
            nav_perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nav_perfilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_perfil)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        nav_perfilLayout.setVerticalGroup(
            nav_perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nav_perfilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_perfil)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        nav_contato.setBackground(new java.awt.Color(54, 164, 255));
        nav_contato.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nav_contato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nav_contatoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nav_contatoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nav_contatoMouseExited(evt);
            }
        });

        label_contato.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        label_contato.setForeground(new java.awt.Color(255, 255, 255));
        label_contato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/integrador/escola/modelos/telas/tela_aluno/images/icon_contato.png"))); // NOI18N
        label_contato.setText("Contato");

        javax.swing.GroupLayout nav_contatoLayout = new javax.swing.GroupLayout(nav_contato);
        nav_contato.setLayout(nav_contatoLayout);
        nav_contatoLayout.setHorizontalGroup(
            nav_contatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nav_contatoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_contato, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        nav_contatoLayout.setVerticalGroup(
            nav_contatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nav_contatoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_contato)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        nav_diario.setBackground(new java.awt.Color(54, 164, 255));
        nav_diario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nav_diario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nav_diarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nav_diarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nav_diarioMouseExited(evt);
            }
        });

        label_diario.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        label_diario.setForeground(new java.awt.Color(255, 255, 255));
        label_diario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/integrador/escola/modelos/telas/tela_aluno/images/icon_carteira.png"))); // NOI18N
        label_diario.setText("Diário");

        javax.swing.GroupLayout nav_diarioLayout = new javax.swing.GroupLayout(nav_diario);
        nav_diario.setLayout(nav_diarioLayout);
        nav_diarioLayout.setHorizontalGroup(
            nav_diarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nav_diarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_diario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        nav_diarioLayout.setVerticalGroup(
            nav_diarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nav_diarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_diario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout navbarLayout = new javax.swing.GroupLayout(navbar);
        navbar.setLayout(navbarLayout);
        navbarLayout.setHorizontalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarLayout.createSequentialGroup()
                .addGroup(navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nav_contato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nav_ocorrencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nav_turmas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nav_perfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nav_inicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nav_diario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        navbarLayout.setVerticalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navbarLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(nav_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nav_perfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nav_diario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nav_turmas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nav_ocorrencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nav_contato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(234, 234, 234))
        );

        getContentPane().add(navbar);
        navbar.setBounds(0, 0, 140, 650);

        javax.swing.GroupLayout rendererLayout = new javax.swing.GroupLayout(renderer);
        renderer.setLayout(rendererLayout);
        rendererLayout.setHorizontalGroup(
            rendererLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        rendererLayout.setVerticalGroup(
            rendererLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        getContentPane().add(renderer);
        renderer.setBounds(140, 90, 590, 480);

        jPanel1.setBackground(new java.awt.Color(232, 180, 88));

        topBar_perfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        topBar_perfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/integrador/escola/modelos/telas/tela_aluno/images/icon_person.png"))); // NOI18N
        topBar_perfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        topBar_perfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                topBar_perfilMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                topBar_perfilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                topBar_perfilMouseExited(evt);
            }
        });

        topBar_nome.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        topBar_nome.setForeground(new java.awt.Color(255, 255, 255));
        topBar_nome.setText(" ");

        button_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/integrador/escola/modelos/telas/tela_aluno/images/icon_close.png"))); // NOI18N
        button_close.setText("jLabel1");
        button_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_closeMouseClicked(evt);
            }
        });

        button_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/integrador/escola/modelos/telas/tela_aluno/images/icon_logout.png"))); // NOI18N
        button_logout.setText("jLabel2");
        button_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_logoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(topBar_perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(topBar_nome, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(button_close, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(topBar_perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(button_close, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(button_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(topBar_nome))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(25, 25, 25)))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(140, 0, 590, 90);

        setSize(new java.awt.Dimension(728, 565));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void getTopBarData(int idPessoa, int idProfessor) throws SQLException {        
        Connection myConn = (Connection) MySQL_Connection.createConnection();
        String mySqlQuery1 = ("SELECT nome from pessoa where idPessoa = " + idPessoa);
        Statement statement_pes = myConn.createStatement();
        
        ResultSet dados_pes = statement_pes.executeQuery(mySqlQuery1);      
        
        dados_pes.next();
        
        topBar_nome.setText(dados_pes.getString("nome"));
    }
    
    public void setNavColor (JPanel p)
    {
        p.setBackground(new Color(232,180,88));
    }

    public void resetNavColor (JPanel p)
    {
        p.setBackground(new Color(54,164,255));
    }
    
    private void nav_inicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_inicioMouseEntered
        setNavColor(nav_inicio);
    }//GEN-LAST:event_nav_inicioMouseEntered

    private void nav_inicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_inicioMouseExited
        resetNavColor(nav_inicio);
    }//GEN-LAST:event_nav_inicioMouseExited

    
    private void nav_turmasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_turmasMouseEntered
        setNavColor(nav_turmas);
    }//GEN-LAST:event_nav_turmasMouseEntered

    private void nav_turmasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_turmasMouseExited
        resetNavColor(nav_turmas);
    }//GEN-LAST:event_nav_turmasMouseExited

    
    
    
    private void nav_ocorrenciasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_ocorrenciasMouseEntered
        setNavColor(nav_ocorrencias);
    }//GEN-LAST:event_nav_ocorrenciasMouseEntered

    private void nav_ocorrenciasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_ocorrenciasMouseExited
        resetNavColor(nav_ocorrencias);
    }//GEN-LAST:event_nav_ocorrenciasMouseExited

    
    private void nav_perfilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_perfilMouseEntered
        setNavColor(nav_perfil);
    }//GEN-LAST:event_nav_perfilMouseEntered

    private void nav_perfilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_perfilMouseExited
        resetNavColor(nav_perfil);
    }//GEN-LAST:event_nav_perfilMouseExited

    
    private void nav_contatoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_contatoMouseEntered
        setNavColor(nav_contato);
    }//GEN-LAST:event_nav_contatoMouseEntered

    private void nav_contatoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_contatoMouseExited

        resetNavColor(nav_contato);
    }//GEN-LAST:event_nav_contatoMouseExited
   
    private void button_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_closeMouseClicked
        int opt = JOptionPane.showConfirmDialog(rootPane, "Deseja sair do aplicativo?", "Sair", 0);
        if (opt == 0) 
        {
            System.exit(0);
        }
    }//GEN-LAST:event_button_closeMouseClicked

    
    page_inicio inicio = new page_inicio();
    page_perfil perfil = new page_perfil();
    page_diario diario = new page_diario();
    page_turmas turmas = new page_turmas();
    page_ocorrencias ocorrencias = new page_ocorrencias();
    page_contato contato = new page_contato();
    
    private void open_page(Component comp) {
        renderer.removeAll();
        renderer.add(comp).setVisible(true);
    }
    
    private void nav_inicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_inicioMouseClicked
        open_page(inicio);
    }//GEN-LAST:event_nav_inicioMouseClicked
    
    private void nav_perfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_perfilMouseClicked
        open_page(perfil);
        
    }//GEN-LAST:event_nav_perfilMouseClicked

    private void nav_turmasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_turmasMouseClicked
        open_page(turmas);
    }//GEN-LAST:event_nav_turmasMouseClicked

    private void nav_ocorrenciasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_ocorrenciasMouseClicked
        open_page(ocorrencias);
    }//GEN-LAST:event_nav_ocorrenciasMouseClicked

    private void nav_contatoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_contatoMouseClicked
        open_page(contato);
    }//GEN-LAST:event_nav_contatoMouseClicked

    private void topBar_perfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topBar_perfilMouseClicked
        open_page(perfil);
    }//GEN-LAST:event_topBar_perfilMouseClicked

    private void topBar_perfilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topBar_perfilMouseEntered
        topBar_perfil.setBorder(BorderFactory.createLineBorder(Color.white));
    }//GEN-LAST:event_topBar_perfilMouseEntered

    private void topBar_perfilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topBar_perfilMouseExited
        topBar_perfil.setBorder(null);
    }//GEN-LAST:event_topBar_perfilMouseExited

    private void nav_diarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_diarioMouseClicked
        open_page(diario);
    }//GEN-LAST:event_nav_diarioMouseClicked

    private void nav_diarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_diarioMouseEntered
        setNavColor(nav_diario);
    }//GEN-LAST:event_nav_diarioMouseEntered

    private void nav_diarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_diarioMouseExited
        resetNavColor(nav_diario);
    }//GEN-LAST:event_nav_diarioMouseExited

    private void button_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_logoutMouseClicked
        try {
            Main_Login telaLogin = new Main_Login();
            Logout.Logout(this, telaLogin);
        } catch (SQLException ex) {
            Logger.getLogger(Tela_Professor.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_button_logoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Tela_Professor().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Tela_Professor.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel button_close;
    private javax.swing.JLabel button_logout;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_contato;
    private javax.swing.JLabel label_diario;
    private javax.swing.JLabel label_inicio;
    private javax.swing.JLabel label_ocorrencias;
    private javax.swing.JLabel label_perfil;
    private javax.swing.JLabel label_turmas;
    private javax.swing.JPanel nav_contato;
    private javax.swing.JPanel nav_diario;
    private javax.swing.JPanel nav_inicio;
    private javax.swing.JPanel nav_ocorrencias;
    private javax.swing.JPanel nav_perfil;
    private javax.swing.JPanel nav_turmas;
    private javax.swing.JPanel navbar;
    private javax.swing.JDesktopPane renderer;
    private javax.swing.JLabel topBar_nome;
    private javax.swing.JLabel topBar_perfil;
    // End of variables declaration//GEN-END:variables
}
