package br.com.senac.integrador.escola.modelos.telas;

import br.com.senac.integrador.escola.modelos.Endereco;
import br.com.senac.integrador.escola.modelos.Estudante;
import br.com.senac.integrador.escola.modelos.Titular;
import br.com.senac.integrador.escola.modelos.auxiliares.JFrameManager;
import br.com.senac.integrador.escola.modelos.auxiliares.Manager;
import br.com.senac.integrador.escola.modelos.auxiliares.Placeholder;
import br.com.senac.integrador.escola.modelos.auxiliares.SQLManager;
import br.com.senac.integrador.escola.modelos.enums.*;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * Definicação da tela de cadastro de professores
 * @author Felipe Godinho Dal Molin
 */
public class CadastroEstudante extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroProfessor
     */
    public CadastroEstudante() {
        initComponents();
        SQLManager.initConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        background = new javax.swing.JPanel();
        content = new javax.swing.JPanel();
        jPanelPessoa = new javax.swing.JPanel();
        campoTelefone = new javax.swing.JTextField();
        campoEmail = new javax.swing.JTextField();
        labelNome = new javax.swing.JLabel();
        labelCPF = new javax.swing.JLabel();
        labelTelefone = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        campoCPF = new javax.swing.JTextField();
        labelRG = new javax.swing.JLabel();
        campoRG = new javax.swing.JTextField();
        labelDeficiencia = new javax.swing.JLabel();
        campoDeficiencia = new javax.swing.JTextField();
        jPanelEndereco = new javax.swing.JPanel();
        campoBairro = new javax.swing.JTextField();
        labelNumero = new javax.swing.JLabel();
        campoNumero = new javax.swing.JTextField();
        labelEndereco = new javax.swing.JLabel();
        campoEndereco = new javax.swing.JTextField();
        labelCidade = new javax.swing.JLabel();
        campoCidade = new javax.swing.JTextField();
        labelCidade1 = new javax.swing.JLabel();
        campoEstado = new javax.swing.JTextField();
        labelBairro = new javax.swing.JLabel();
        campoNacionalidade = new javax.swing.JTextField();
        labelNacionalidade = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labelDataNascimento = new javax.swing.JLabel();
        campoDataNascimento = new javax.swing.JTextField();
        labelNomeResponsavel = new javax.swing.JLabel();
        campoEmailResponsavel = new javax.swing.JTextField();
        botaoCadastrar = new javax.swing.JButton();
        comboBoxGenero = new javax.swing.JComboBox<>();
        comboBoxEstadoCivil = new javax.swing.JComboBox<>();
        comboBoxCorRaca = new javax.swing.JComboBox<>();
        comboBoxEscolaridade = new javax.swing.JComboBox<>();
        radioButtonTrabalha = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        labelIdLogin = new javax.swing.JLabel();
        campoIdLogin = new javax.swing.JTextField();
        title = new javax.swing.JPanel();
        titleMain = new javax.swing.JLabel();
        sidePanel = new javax.swing.JPanel();
        cadastrarProfessor = new javax.swing.JPanel();
        icon = new javax.swing.JLabel();
        labelSection = new javax.swing.JLabel();
        verProfessores = new javax.swing.JPanel();
        icon1 = new javax.swing.JLabel();
        labelSection1 = new javax.swing.JLabel();
        cadastrarEstudante = new javax.swing.JPanel();
        iconEstudante = new javax.swing.JLabel();
        labelSectionEstudante = new javax.swing.JLabel();
        verEstudantes = new javax.swing.JPanel();
        icon2 = new javax.swing.JLabel();
        labelVerEstudantes = new javax.swing.JLabel();
        cadastroLogin = new javax.swing.JPanel();
        icon5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastrar Estudante");

        background.setBackground(new java.awt.Color(255, 255, 255));

        content.setBackground(new java.awt.Color(75, 97, 148));
        content.setAutoscrolls(true);
        content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelPessoa.setBackground(new java.awt.Color(19, 16, 89));

        campoTelefone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoTelefone.setForeground(new java.awt.Color(153, 153, 153));
        campoTelefone.setText("XX (XXX) XXXXX-XXXX");
        campoTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoTelefoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoTelefoneFocusLost(evt);
            }
        });

        campoEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoEmail.setForeground(new java.awt.Color(153, 153, 153));
        campoEmail.setText("nome@empresa");
        campoEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoEmailFocusLost(evt);
            }
        });

        labelNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNome.setForeground(new java.awt.Color(255, 255, 255));
        labelNome.setText("Nome:");

        labelCPF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelCPF.setForeground(new java.awt.Color(255, 255, 255));
        labelCPF.setText("CPF:");

        labelTelefone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTelefone.setForeground(new java.awt.Color(255, 255, 255));
        labelTelefone.setText("Telefone:");

        labelEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelEmail.setForeground(new java.awt.Color(255, 255, 255));
        labelEmail.setText("E-mail:");

        campoNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoNome.setForeground(new java.awt.Color(0, 0, 0));

        campoCPF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoCPF.setForeground(new java.awt.Color(153, 153, 153));
        campoCPF.setText("XXX.XXX.XXX-XX");
        campoCPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoCPFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoCPFFocusLost(evt);
            }
        });

        labelRG.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelRG.setForeground(new java.awt.Color(255, 255, 255));
        labelRG.setText("RG:");

        campoRG.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoRG.setForeground(new java.awt.Color(153, 153, 153));
        campoRG.setText("X.XXX.XXX");
        campoRG.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoRGFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoRGFocusLost(evt);
            }
        });

        labelDeficiencia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelDeficiencia.setForeground(new java.awt.Color(255, 255, 255));
        labelDeficiencia.setText("Deficiência:");

        campoDeficiencia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoDeficiencia.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanelPessoaLayout = new javax.swing.GroupLayout(jPanelPessoa);
        jPanelPessoa.setLayout(jPanelPessoaLayout);
        jPanelPessoaLayout.setHorizontalGroup(
            jPanelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPessoaLayout.createSequentialGroup()
                .addGroup(jPanelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(labelDeficiencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelTelefone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelCPF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelRG, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoNome)
                    .addComponent(campoCPF)
                    .addComponent(campoTelefone)
                    .addComponent(campoEmail)
                    .addComponent(campoRG)
                    .addComponent(campoDeficiencia)))
        );
        jPanelPessoaLayout.setVerticalGroup(
            jPanelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPessoaLayout.createSequentialGroup()
                .addGroup(jPanelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRG, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDeficiencia, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoDeficiencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        content.add(jPanelPessoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jPanelEndereco.setBackground(new java.awt.Color(19, 16, 89));

        campoBairro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoBairro.setForeground(new java.awt.Color(0, 0, 0));

        labelNumero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNumero.setForeground(new java.awt.Color(255, 255, 255));
        labelNumero.setText("Número:");

        campoNumero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoNumero.setForeground(new java.awt.Color(0, 0, 0));

        labelEndereco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelEndereco.setForeground(new java.awt.Color(255, 255, 255));
        labelEndereco.setText("Endereço:");

        campoEndereco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoEndereco.setForeground(new java.awt.Color(0, 0, 0));

        labelCidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelCidade.setForeground(new java.awt.Color(255, 255, 255));
        labelCidade.setText("Cidade:");

        campoCidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoCidade.setForeground(new java.awt.Color(0, 0, 0));

        labelCidade1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelCidade1.setForeground(new java.awt.Color(255, 255, 255));
        labelCidade1.setText("Estado:");

        campoEstado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoEstado.setForeground(new java.awt.Color(153, 153, 153));
        campoEstado.setText("RS, SC, PR...");
        campoEstado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoEstadoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoEstadoFocusLost(evt);
            }
        });

        labelBairro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelBairro.setForeground(new java.awt.Color(255, 255, 255));
        labelBairro.setText("Bairro:");

        campoNacionalidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoNacionalidade.setForeground(new java.awt.Color(0, 0, 0));

        labelNacionalidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNacionalidade.setForeground(new java.awt.Color(255, 255, 255));
        labelNacionalidade.setText("Nacionalidade:");

        javax.swing.GroupLayout jPanelEnderecoLayout = new javax.swing.GroupLayout(jPanelEndereco);
        jPanelEndereco.setLayout(jPanelEnderecoLayout);
        jPanelEnderecoLayout.setHorizontalGroup(
            jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                    .addComponent(labelCidade1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(campoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                        .addComponent(labelCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                        .addComponent(labelBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                        .addComponent(labelNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEnderecoLayout.createSequentialGroup()
                .addComponent(labelEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEnderecoLayout.createSequentialGroup()
                .addComponent(labelNacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoNacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelEnderecoLayout.setVerticalGroup(
            jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCidade1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(campoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        content.add(jPanelEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, -1, -1));

        jPanel1.setBackground(new java.awt.Color(19, 16, 89));

        labelDataNascimento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelDataNascimento.setForeground(new java.awt.Color(255, 255, 255));
        labelDataNascimento.setText("Data de nascimento:");

        campoDataNascimento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoDataNascimento.setForeground(new java.awt.Color(153, 153, 153));
        campoDataNascimento.setText("DD/MM/AAAA");
        campoDataNascimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoDataNascimentoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoDataNascimentoFocusLost(evt);
            }
        });

        labelNomeResponsavel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNomeResponsavel.setForeground(new java.awt.Color(255, 255, 255));
        labelNomeResponsavel.setText("Nome do responsável:");

        campoEmailResponsavel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoEmailResponsavel.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(labelDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoDataNascimento))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(labelNomeResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoEmailResponsavel, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoEmailResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        content.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 270, 70));

        botaoCadastrar.setBackground(new java.awt.Color(19, 16, 89));
        botaoCadastrar.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        botaoCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        botaoCadastrar.setText("Cadastrar Aluno");
        botaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarActionPerformed(evt);
            }
        });
        content.add(botaoCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 350, -1, -1));

        comboBoxGenero.setBackground(new java.awt.Color(19, 16, 89));
        comboBoxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { Genero.MASCULINO.name(), Genero.FEMININO.name(), Genero.OUTRO.name()}));
        content.add(comboBoxGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, 140, -1));

        comboBoxEstadoCivil.setBackground(new java.awt.Color(19, 16, 89));
        comboBoxEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {
            EstadoCivil.SOLTEIRO.name(),
            EstadoCivil.CASADO.name(),
            EstadoCivil.DIVORCIADO.name(),
            EstadoCivil.VIUVO.name() }));
content.add(comboBoxEstadoCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, 140, -1));

comboBoxCorRaca.setBackground(new java.awt.Color(19, 16, 89));
comboBoxCorRaca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {
    CorRaca.BRANCO.name(),
    CorRaca.PARDO.name(),
    CorRaca.NEGRO.name(),
    CorRaca.INDIGENA.name(),
    CorRaca.AMARELO.name() }));
    content.add(comboBoxCorRaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 270, 140, -1));

    comboBoxEscolaridade.setBackground(new java.awt.Color(19, 16, 89));
    comboBoxEscolaridade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {
        Escolaridade.FUNDAMENTAL.name(),
        Escolaridade.MEDIO.name(),
        Escolaridade.SUPERIOR.name() }));
content.add(comboBoxEscolaridade, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 140, -1));

radioButtonTrabalha.setBackground(new java.awt.Color(19, 16, 89));
radioButtonTrabalha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
radioButtonTrabalha.setText("Está trabalhando");
content.add(radioButtonTrabalha, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, -1, -1));

jPanel3.setBackground(new java.awt.Color(19, 16, 89));

labelIdLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
labelIdLogin.setForeground(new java.awt.Color(255, 255, 255));
labelIdLogin.setText("Código de login:");

javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
jPanel3.setLayout(jPanel3Layout);
jPanel3Layout.setHorizontalGroup(
jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(jPanel3Layout.createSequentialGroup()
    .addComponent(labelIdLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    .addComponent(campoIdLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addGap(18, 18, 18))
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(labelIdLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(campoIdLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(0, 2, Short.MAX_VALUE))
    );

    content.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 240, 30));

    title.setBackground(new java.awt.Color(10, 23, 82));

    titleMain.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
    titleMain.setForeground(new java.awt.Color(255, 255, 255));
    titleMain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    titleMain.setText("Cadastrar Estudante");

    javax.swing.GroupLayout titleLayout = new javax.swing.GroupLayout(title);
    title.setLayout(titleLayout);
    titleLayout.setHorizontalGroup(
        titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(titleMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    titleLayout.setVerticalGroup(
        titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(titleMain, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
    );

    sidePanel.setBackground(new java.awt.Color(19, 16, 89));

    cadastrarProfessor.setBackground(new java.awt.Color(19, 16, 89));
    cadastrarProfessor.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            cadastrarProfessorMouseClicked(evt);
        }
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            cadastrarProfessorMouseEntered(evt);
        }
        public void mouseExited(java.awt.event.MouseEvent evt) {
            cadastrarProfessorMouseExited(evt);
        }
    });

    icon.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
    icon.setForeground(new java.awt.Color(255, 255, 255));
    icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/integrador/escola/images/75px/Adicionar_Cadastro75px.png"))); // NOI18N

    labelSection.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    labelSection.setForeground(new java.awt.Color(255, 255, 255));
    labelSection.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    labelSection.setText("Cadastrar Professor");

    javax.swing.GroupLayout cadastrarProfessorLayout = new javax.swing.GroupLayout(cadastrarProfessor);
    cadastrarProfessor.setLayout(cadastrarProfessorLayout);
    cadastrarProfessorLayout.setHorizontalGroup(
        cadastrarProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(cadastrarProfessorLayout.createSequentialGroup()
            .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, 0)
            .addComponent(labelSection, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
    );
    cadastrarProfessorLayout.setVerticalGroup(
        cadastrarProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(labelSection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    verProfessores.setBackground(new java.awt.Color(19, 16, 89));
    verProfessores.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            verProfessoresMouseClicked(evt);
        }
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            verProfessoresMouseEntered(evt);
        }
        public void mouseExited(java.awt.event.MouseEvent evt) {
            verProfessoresMouseExited(evt);
        }
    });

    icon1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
    icon1.setForeground(new java.awt.Color(255, 255, 255));
    icon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/integrador/escola/images/75px/ver_cadastros_professor_75px.png"))); // NOI18N

    labelSection1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    labelSection1.setForeground(new java.awt.Color(255, 255, 255));
    labelSection1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    labelSection1.setText("Ver Professores");

    javax.swing.GroupLayout verProfessoresLayout = new javax.swing.GroupLayout(verProfessores);
    verProfessores.setLayout(verProfessoresLayout);
    verProfessoresLayout.setHorizontalGroup(
        verProfessoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, verProfessoresLayout.createSequentialGroup()
            .addComponent(icon1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, 0)
            .addComponent(labelSection1, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
    );
    verProfessoresLayout.setVerticalGroup(
        verProfessoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(icon1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(labelSection1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    cadastrarEstudante.setBackground(new java.awt.Color(19, 16, 89));
    cadastrarEstudante.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            cadastrarEstudanteMouseClicked(evt);
        }
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            cadastrarEstudanteMouseEntered(evt);
        }
        public void mouseExited(java.awt.event.MouseEvent evt) {
            cadastrarEstudanteMouseExited(evt);
        }
    });

    iconEstudante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    iconEstudante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/integrador/escola/images/75px/Adicionar_Cadastro75px.png"))); // NOI18N

    labelSectionEstudante.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    labelSectionEstudante.setForeground(new java.awt.Color(255, 255, 255));
    labelSectionEstudante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    labelSectionEstudante.setText("Cadastrar Estudante");

    javax.swing.GroupLayout cadastrarEstudanteLayout = new javax.swing.GroupLayout(cadastrarEstudante);
    cadastrarEstudante.setLayout(cadastrarEstudanteLayout);
    cadastrarEstudanteLayout.setHorizontalGroup(
        cadastrarEstudanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(cadastrarEstudanteLayout.createSequentialGroup()
            .addComponent(iconEstudante, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, 0)
            .addComponent(labelSectionEstudante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    cadastrarEstudanteLayout.setVerticalGroup(
        cadastrarEstudanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(iconEstudante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(labelSectionEstudante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    verEstudantes.setBackground(new java.awt.Color(19, 16, 89));
    verEstudantes.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            verEstudantesMouseClicked(evt);
        }
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            verEstudantesMouseEntered(evt);
        }
        public void mouseExited(java.awt.event.MouseEvent evt) {
            verEstudantesMouseExited(evt);
        }
    });

    icon2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/integrador/escola/images/75px/ver_cadastros_professor_75px.png"))); // NOI18N

    labelVerEstudantes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    labelVerEstudantes.setForeground(new java.awt.Color(255, 255, 255));
    labelVerEstudantes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    labelVerEstudantes.setText("Ver Estudantes");

    javax.swing.GroupLayout verEstudantesLayout = new javax.swing.GroupLayout(verEstudantes);
    verEstudantes.setLayout(verEstudantesLayout);
    verEstudantesLayout.setHorizontalGroup(
        verEstudantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(verEstudantesLayout.createSequentialGroup()
            .addComponent(icon2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, 0)
            .addComponent(labelVerEstudantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    verEstudantesLayout.setVerticalGroup(
        verEstudantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(icon2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(labelVerEstudantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    cadastroLogin.setBackground(new java.awt.Color(19, 16, 89));
    cadastroLogin.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            cadastroLoginMouseClicked(evt);
        }
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            cadastroLoginMouseEntered(evt);
        }
        public void mouseExited(java.awt.event.MouseEvent evt) {
            cadastroLoginMouseExited(evt);
        }
    });

    icon5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    icon5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/integrador/escola/images/75px/Adicionar_Cadastro75px.png"))); // NOI18N

    jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel6.setForeground(new java.awt.Color(255, 255, 255));
    jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel6.setText("Cadastrar Login");

    javax.swing.GroupLayout cadastroLoginLayout = new javax.swing.GroupLayout(cadastroLogin);
    cadastroLogin.setLayout(cadastroLoginLayout);
    cadastroLoginLayout.setHorizontalGroup(
        cadastroLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(cadastroLoginLayout.createSequentialGroup()
            .addComponent(icon5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, 0)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    cadastroLoginLayout.setVerticalGroup(
        cadastroLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(icon5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
    sidePanel.setLayout(sidePanelLayout);
    sidePanelLayout.setHorizontalGroup(
        sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(cadastrarEstudante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(verEstudantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(sidePanelLayout.createSequentialGroup()
            .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(verProfessores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(cadastrarProfessor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(0, 0, Short.MAX_VALUE))
        .addComponent(cadastroLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    sidePanelLayout.setVerticalGroup(
        sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(sidePanelLayout.createSequentialGroup()
            .addComponent(cadastrarProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, 0)
            .addComponent(verProfessores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, 0)
            .addComponent(cadastrarEstudante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, 0)
            .addComponent(verEstudantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, 0)
            .addComponent(cadastroLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
    background.setLayout(backgroundLayout);
    backgroundLayout.setHorizontalGroup(
        backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(backgroundLayout.createSequentialGroup()
            .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, 0)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 914, Short.MAX_VALUE))
        .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    backgroundLayout.setVerticalGroup(
        backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(backgroundLayout.createSequentialGroup()
            .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void cadastrarProfessorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarProfessorMouseClicked
        JFrameManager.changeJFrame(evt, new CadastroProfessor());
    }//GEN-LAST:event_cadastrarProfessorMouseClicked
    private void cadastrarProfessorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarProfessorMouseEntered
        JFrameManager.sectionMouseEntered(evt);
    }//GEN-LAST:event_cadastrarProfessorMouseEntered
    private void cadastrarProfessorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarProfessorMouseExited
        JFrameManager.sectionMouseExited(evt);
    }//GEN-LAST:event_cadastrarProfessorMouseExited
    private void verProfessoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verProfessoresMouseClicked
        JFrameManager.changeJFrame(evt, new ProfessoresCadastrados());
    }//GEN-LAST:event_verProfessoresMouseClicked
    private void verProfessoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verProfessoresMouseEntered
        JFrameManager.sectionMouseEntered(evt);
    }//GEN-LAST:event_verProfessoresMouseEntered
    private void verProfessoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verProfessoresMouseExited
        JFrameManager.sectionMouseExited(evt);
    }//GEN-LAST:event_verProfessoresMouseExited
    private void cadastrarEstudanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarEstudanteMouseClicked
        JFrameManager.changeJFrame(evt, new CadastroEstudante());
    }//GEN-LAST:event_cadastrarEstudanteMouseClicked
    private void cadastrarEstudanteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarEstudanteMouseEntered
        JFrameManager.sectionMouseEntered(evt);
    }//GEN-LAST:event_cadastrarEstudanteMouseEntered
    private void cadastrarEstudanteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarEstudanteMouseExited
        JFrameManager.sectionMouseExited(evt);
    }//GEN-LAST:event_cadastrarEstudanteMouseExited
    private void verEstudantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verEstudantesMouseClicked
        JFrameManager.changeJFrame(evt, new EstudantesCadastrados());
    }//GEN-LAST:event_verEstudantesMouseClicked
    private void verEstudantesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verEstudantesMouseEntered
        JFrameManager.sectionMouseEntered(evt);
    }//GEN-LAST:event_verEstudantesMouseEntered
    private void verEstudantesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verEstudantesMouseExited
        JFrameManager.sectionMouseExited(evt);
    }//GEN-LAST:event_verEstudantesMouseExited
    private void campoTelefoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoTelefoneFocusGained
        JFrameManager.campoFocusGained(evt, campoTelefone, Placeholder.TELEFONE);
    }//GEN-LAST:event_campoTelefoneFocusGained
    private void campoTelefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoTelefoneFocusLost
        JFrameManager.campoFocusLost(evt, campoTelefone, Placeholder.TELEFONE);
    }//GEN-LAST:event_campoTelefoneFocusLost
    private void campoCPFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCPFFocusGained
        JFrameManager.campoFocusGained(evt, campoCPF, Placeholder.CPF);
    }//GEN-LAST:event_campoCPFFocusGained
    private void campoCPFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCPFFocusLost
        JFrameManager.campoFocusLost(evt, campoCPF, Placeholder.CPF);
    }//GEN-LAST:event_campoCPFFocusLost
    private void campoRGFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoRGFocusGained
        JFrameManager.campoFocusGained(evt, campoRG, Placeholder.RG);
    }//GEN-LAST:event_campoRGFocusGained
    private void campoRGFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoRGFocusLost
        JFrameManager.campoFocusLost(evt, campoRG, Placeholder.RG);
    }//GEN-LAST:event_campoRGFocusLost
    private void campoEstadoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoEstadoFocusGained
        JFrameManager.campoFocusGained(evt, campoEstado, Placeholder.ESTADO);
    }//GEN-LAST:event_campoEstadoFocusGained
    private void campoEstadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoEstadoFocusLost
        JFrameManager.campoFocusLost(evt, campoEstado, Placeholder.ESTADO);
    }//GEN-LAST:event_campoEstadoFocusLost
    private void campoDataNascimentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoDataNascimentoFocusGained
        JFrameManager.campoFocusGained(evt, campoDataNascimento, Placeholder.DATANASCIMENTO);
    }//GEN-LAST:event_campoDataNascimentoFocusGained
    private void campoDataNascimentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoDataNascimentoFocusLost
        JFrameManager.campoFocusLost(evt, campoDataNascimento, Placeholder.DATANASCIMENTO);
    }//GEN-LAST:event_campoDataNascimentoFocusLost

    private void botaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarActionPerformed
        int idLogin = Integer.parseInt(campoIdLogin.getText());
        
        String nome = campoNome.getText();
        String cpf = campoCPF.getText();
        String rg = campoRG.getText();
        String telefone = campoTelefone.getText();
        String email = campoEmail.getText();
        String deficiencia = campoDeficiencia.getText();
        
        String estado = campoEstado.getText();
        String cidade = campoCidade.getText();
        String bairro = campoBairro.getText();
        String numero = campoNumero.getText();
        String endereco = campoEmail.getText();
        String nacionalidade = campoNacionalidade.getText();
        
        String indicadorGenero = (String) comboBoxGenero.getSelectedItem();
        String indicadorEstadoCivil = (String) comboBoxEstadoCivil.getSelectedItem();
        String indicadorEscolaridade = (String) comboBoxEscolaridade.getSelectedItem();
        String indicadorCorRaca = (String) comboBoxCorRaca.getSelectedItem();

        Genero genero = Enum.valueOf(Genero.class, indicadorGenero);
        EstadoCivil estadoCivil = Enum.valueOf(EstadoCivil.class, indicadorEstadoCivil);
        Escolaridade escolaridade = Enum.valueOf(Escolaridade.class, indicadorEscolaridade);
        CorRaca corRaca = Enum.valueOf(CorRaca.class, indicadorCorRaca);
        
        boolean trabalha = radioButtonTrabalha.isEnabled();
        
        String dataNascimentoTexto = campoDataNascimento.getText();
        String emailResponsavel = campoEmailResponsavel.getText();
        
        LocalDate dataNascimento = LocalDate.parse(dataNascimentoTexto, Manager.formatter);
        
        
        Titular titular = new Titular(nome, cpf, rg, telefone, email, nacionalidade, deficiencia, dataNascimento);
        Endereco ender = new Endereco(estado, cidade, bairro, Integer.parseInt(numero), endereco);
        Estudante estudante = new Estudante(titular, ender, estadoCivil, genero, corRaca, emailResponsavel, trabalha, escolaridade);
        estudante.setIdLogin(idLogin);
        try {
            SQLManager.cadastrar(estudante);
        } catch (SQLException ex) {
            Logger.getLogger(CadastroEstudante.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        JOptionPane.showMessageDialog(null, "Estudante cadastrado.");
    }//GEN-LAST:event_botaoCadastrarActionPerformed

    private void campoEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoEmailFocusGained
       JFrameManager.campoFocusGained(evt, campoEmail, Placeholder.EMAIL);
    }//GEN-LAST:event_campoEmailFocusGained

    private void campoEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoEmailFocusLost
       JFrameManager.campoFocusLost(evt, campoCPF, Placeholder.EMAIL);
    }//GEN-LAST:event_campoEmailFocusLost

    private void cadastroLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastroLoginMouseClicked
        JFrameManager.changeJFrame(evt, new CadastroLogin());
    }//GEN-LAST:event_cadastroLoginMouseClicked

    private void cadastroLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastroLoginMouseEntered
        JFrameManager.sectionMouseEntered(evt);
    }//GEN-LAST:event_cadastroLoginMouseEntered

    private void cadastroLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastroLoginMouseExited
        JFrameManager.sectionMouseExited(evt);
    }//GEN-LAST:event_cadastroLoginMouseExited
    
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroEstudante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroEstudante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroEstudante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroEstudante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroEstudante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JPanel cadastrarEstudante;
    private javax.swing.JPanel cadastrarProfessor;
    private javax.swing.JPanel cadastroLogin;
    private javax.swing.JTextField campoBairro;
    private javax.swing.JTextField campoCPF;
    private javax.swing.JTextField campoCidade;
    private javax.swing.JTextField campoDataNascimento;
    private javax.swing.JTextField campoDeficiencia;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoEmailResponsavel;
    private javax.swing.JTextField campoEndereco;
    private javax.swing.JTextField campoEstado;
    private javax.swing.JTextField campoIdLogin;
    private javax.swing.JTextField campoNacionalidade;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoNumero;
    private javax.swing.JTextField campoRG;
    private javax.swing.JTextField campoTelefone;
    private javax.swing.JComboBox<String> comboBoxCorRaca;
    private javax.swing.JComboBox<String> comboBoxEscolaridade;
    private javax.swing.JComboBox<String> comboBoxEstadoCivil;
    private javax.swing.JComboBox<String> comboBoxGenero;
    private javax.swing.JPanel content;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel icon1;
    private javax.swing.JLabel icon2;
    private javax.swing.JLabel icon5;
    private javax.swing.JLabel iconEstudante;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelEndereco;
    private javax.swing.JPanel jPanelPessoa;
    private javax.swing.JLabel labelBairro;
    private javax.swing.JLabel labelCPF;
    private javax.swing.JLabel labelCidade;
    private javax.swing.JLabel labelCidade1;
    private javax.swing.JLabel labelDataNascimento;
    private javax.swing.JLabel labelDeficiencia;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelEndereco;
    private javax.swing.JLabel labelIdLogin;
    private javax.swing.JLabel labelNacionalidade;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelNomeResponsavel;
    private javax.swing.JLabel labelNumero;
    private javax.swing.JLabel labelRG;
    private javax.swing.JLabel labelSection;
    private javax.swing.JLabel labelSection1;
    private javax.swing.JLabel labelSectionEstudante;
    private javax.swing.JLabel labelTelefone;
    private javax.swing.JLabel labelVerEstudantes;
    private javax.swing.JRadioButton radioButtonTrabalha;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JPanel title;
    private javax.swing.JLabel titleMain;
    private javax.swing.JPanel verEstudantes;
    private javax.swing.JPanel verProfessores;
    // End of variables declaration//GEN-END:variables
}