package br.com.senac.integrador.escola.modelos.telas;

import br.com.senac.integrador.escola.modelos.Endereco;
import br.com.senac.integrador.escola.modelos.enums.EstadoCivil;
import br.com.senac.integrador.escola.modelos.auxiliares.Manager;
import br.com.senac.integrador.escola.modelos.Professor;
import br.com.senac.integrador.escola.modelos.Titular;
import br.com.senac.integrador.escola.modelos.auxiliares.JFrameManager;
import br.com.senac.integrador.escola.modelos.auxiliares.Placeholder;
import br.com.senac.integrador.escola.modelos.auxiliares.SQLManager;
import br.com.senac.integrador.escola.modelos.enums.CorRaca;
import br.com.senac.integrador.escola.modelos.enums.Genero;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;

/**
 * Definicação da tela de cadastro de professores
 * @author Felipe Godinho Dal Molin
 */
public class CadastroProfessor extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroProfessor
     */
    public CadastroProfessor() {
        initComponents();
        SQLManager.initConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotoesEstadoCivil = new javax.swing.ButtonGroup();
        grupoBotoesCorRaca = new javax.swing.ButtonGroup();
        grupoBotoesGenero = new javax.swing.ButtonGroup();
        background = new javax.swing.JPanel();
        content = new javax.swing.JPanel();
        jPanelEstadoCivil = new javax.swing.JPanel();
        botaoSolteiro = new javax.swing.JRadioButton();
        botaoCasado = new javax.swing.JRadioButton();
        botaoDivorciado = new javax.swing.JRadioButton();
        botaoViuvo = new javax.swing.JRadioButton();
        titleEstadoCivil = new javax.swing.JLabel();
        jPanelEndereco = new javax.swing.JPanel();
        campoBairro = new javax.swing.JTextField();
        labelNumero = new javax.swing.JLabel();
        campoNumero = new javax.swing.JTextField();
        labelEndereco = new javax.swing.JLabel();
        campoEndereco = new javax.swing.JTextField();
        labelCidade = new javax.swing.JLabel();
        campoCidade = new javax.swing.JTextField();
        labelCidade1 = new javax.swing.JLabel();
        campoEstado = new javax.swing.JTextField();
        labelBairro = new javax.swing.JLabel();
        campoNacionalidade = new javax.swing.JTextField();
        labelNacionalidade = new javax.swing.JLabel();
        labelDataNascimento = new javax.swing.JLabel();
        campoDataNascimento = new javax.swing.JTextField();
        jPanelPessoa = new javax.swing.JPanel();
        campoTelefone = new javax.swing.JTextField();
        campoEmail = new javax.swing.JTextField();
        labelNome = new javax.swing.JLabel();
        labelCPF = new javax.swing.JLabel();
        labelTelefone = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        campoCPF = new javax.swing.JTextField();
        labelRG = new javax.swing.JLabel();
        campoRG = new javax.swing.JTextField();
        labelDeficiencia = new javax.swing.JLabel();
        campoDeficiencia = new javax.swing.JTextField();
        labelIdLogin = new javax.swing.JLabel();
        campoIdLogin = new javax.swing.JTextField();
        jPanelFormacao = new javax.swing.JPanel();
        titleFormacao = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoFormacao = new javax.swing.JTextArea();
        botaoCadastrar = new javax.swing.JButton();
        jPanelCorRaca = new javax.swing.JPanel();
        botaoBranco = new javax.swing.JRadioButton();
        botaoPardo = new javax.swing.JRadioButton();
        botaoNegro = new javax.swing.JRadioButton();
        botaoAmarelo = new javax.swing.JRadioButton();
        botaoIndigena = new javax.swing.JRadioButton();
        titleCorRaca = new javax.swing.JLabel();
        jPanelGenero = new javax.swing.JPanel();
        botaoMasculino = new javax.swing.JRadioButton();
        botaoFeminino = new javax.swing.JRadioButton();
        botaoOutro = new javax.swing.JRadioButton();
        titleGenero = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        titleHistoricoProfissional = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        campoHistoricoProfissional = new javax.swing.JTextArea();
        title = new javax.swing.JPanel();
        titleMain = new javax.swing.JLabel();
        sidePanel = new javax.swing.JPanel();
        cadastrarProfessor = new javax.swing.JPanel();
        icon = new javax.swing.JLabel();
        labelSection = new javax.swing.JLabel();
        verProfessores = new javax.swing.JPanel();
        icon1 = new javax.swing.JLabel();
        labelSection1 = new javax.swing.JLabel();
        cadastrarEstudante = new javax.swing.JPanel();
        iconEstudante = new javax.swing.JLabel();
        labelSectionEstudante = new javax.swing.JLabel();
        verEstudantes = new javax.swing.JPanel();
        icon2 = new javax.swing.JLabel();
        labelVerEstudantes = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        labelVerEstudantes1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastrar Professor");

        background.setBackground(new java.awt.Color(255, 255, 255));

        content.setBackground(new java.awt.Color(75, 97, 148));
        content.setAutoscrolls(true);
        content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelEstadoCivil.setBackground(new java.awt.Color(19, 16, 89));

        botaoSolteiro.setBackground(new java.awt.Color(19, 16, 89));
        grupoBotoesEstadoCivil.add(botaoSolteiro);
        botaoSolteiro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoSolteiro.setForeground(new java.awt.Color(255, 255, 255));
        botaoSolteiro.setText("Solteiro(a)");

        botaoCasado.setBackground(new java.awt.Color(19, 16, 89));
        grupoBotoesEstadoCivil.add(botaoCasado);
        botaoCasado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoCasado.setForeground(new java.awt.Color(255, 255, 255));
        botaoCasado.setText("Casado(a)");

        botaoDivorciado.setBackground(new java.awt.Color(19, 16, 89));
        grupoBotoesEstadoCivil.add(botaoDivorciado);
        botaoDivorciado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoDivorciado.setForeground(new java.awt.Color(255, 255, 255));
        botaoDivorciado.setText("Divorciado(a)");

        botaoViuvo.setBackground(new java.awt.Color(19, 16, 89));
        grupoBotoesEstadoCivil.add(botaoViuvo);
        botaoViuvo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoViuvo.setForeground(new java.awt.Color(255, 255, 255));
        botaoViuvo.setText("Viúvo(a)");

        titleEstadoCivil.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titleEstadoCivil.setForeground(new java.awt.Color(255, 255, 255));
        titleEstadoCivil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleEstadoCivil.setText("Estado Civil");

        javax.swing.GroupLayout jPanelEstadoCivilLayout = new javax.swing.GroupLayout(jPanelEstadoCivil);
        jPanelEstadoCivil.setLayout(jPanelEstadoCivilLayout);
        jPanelEstadoCivilLayout.setHorizontalGroup(
            jPanelEstadoCivilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEstadoCivilLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEstadoCivilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoDivorciado)
                    .addComponent(botaoSolteiro)
                    .addComponent(botaoCasado)
                    .addComponent(botaoViuvo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(titleEstadoCivil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelEstadoCivilLayout.setVerticalGroup(
            jPanelEstadoCivilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEstadoCivilLayout.createSequentialGroup()
                .addComponent(titleEstadoCivil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoSolteiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoCasado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoDivorciado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoViuvo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        content.add(jPanelEstadoCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, -1, -1));

        jPanelEndereco.setBackground(new java.awt.Color(19, 16, 89));

        campoBairro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoBairro.setForeground(new java.awt.Color(0, 0, 0));

        labelNumero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNumero.setForeground(new java.awt.Color(255, 255, 255));
        labelNumero.setText("Número:");

        campoNumero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoNumero.setForeground(new java.awt.Color(0, 0, 0));

        labelEndereco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelEndereco.setForeground(new java.awt.Color(255, 255, 255));
        labelEndereco.setText("Endereço:");

        campoEndereco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoEndereco.setForeground(new java.awt.Color(0, 0, 0));

        labelCidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelCidade.setForeground(new java.awt.Color(255, 255, 255));
        labelCidade.setText("Cidade:");

        campoCidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoCidade.setForeground(new java.awt.Color(0, 0, 0));

        labelCidade1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelCidade1.setForeground(new java.awt.Color(255, 255, 255));
        labelCidade1.setText("Estado:");

        campoEstado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoEstado.setForeground(new java.awt.Color(153, 153, 153));
        campoEstado.setText("RS, SC, PR...");
        campoEstado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoEstadoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoEstadoFocusLost(evt);
            }
        });

        labelBairro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelBairro.setForeground(new java.awt.Color(255, 255, 255));
        labelBairro.setText("Bairro:");

        campoNacionalidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoNacionalidade.setForeground(new java.awt.Color(0, 0, 0));

        labelNacionalidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNacionalidade.setForeground(new java.awt.Color(255, 255, 255));
        labelNacionalidade.setText("Nacionalidade:");

        labelDataNascimento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelDataNascimento.setForeground(new java.awt.Color(255, 255, 255));
        labelDataNascimento.setText("Nascimento:");

        campoDataNascimento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoDataNascimento.setForeground(new java.awt.Color(153, 153, 153));
        campoDataNascimento.setText("DD/MM/AAAA");
        campoDataNascimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoDataNascimentoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoDataNascimentoFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanelEnderecoLayout = new javax.swing.GroupLayout(jPanelEndereco);
        jPanelEndereco.setLayout(jPanelEnderecoLayout);
        jPanelEnderecoLayout.setHorizontalGroup(
            jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                    .addComponent(labelCidade1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(campoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                        .addComponent(labelCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                        .addComponent(labelBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                        .addComponent(labelNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEnderecoLayout.createSequentialGroup()
                .addComponent(labelEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEnderecoLayout.createSequentialGroup()
                .addComponent(labelNacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoNacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEnderecoLayout.createSequentialGroup()
                .addComponent(labelDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelEnderecoLayout.setVerticalGroup(
            jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCidade1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(campoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        content.add(jPanelEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, -1, -1));

        jPanelPessoa.setBackground(new java.awt.Color(19, 16, 89));

        campoTelefone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoTelefone.setForeground(new java.awt.Color(153, 153, 153));
        campoTelefone.setText("XX (XXX) XXXXX-XXXX");
        campoTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoTelefoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoTelefoneFocusLost(evt);
            }
        });

        campoEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoEmail.setForeground(new java.awt.Color(0, 0, 0));

        labelNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNome.setForeground(new java.awt.Color(255, 255, 255));
        labelNome.setText("Nome:");

        labelCPF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelCPF.setForeground(new java.awt.Color(255, 255, 255));
        labelCPF.setText("CPF:");

        labelTelefone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTelefone.setForeground(new java.awt.Color(255, 255, 255));
        labelTelefone.setText("Telefone:");

        labelEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelEmail.setForeground(new java.awt.Color(255, 255, 255));
        labelEmail.setText("E-mail:");

        campoNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoNome.setForeground(new java.awt.Color(0, 0, 0));

        campoCPF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoCPF.setForeground(new java.awt.Color(153, 153, 153));
        campoCPF.setText("XXX.XXX.XXX-XX");
        campoCPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoCPFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoCPFFocusLost(evt);
            }
        });

        labelRG.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelRG.setForeground(new java.awt.Color(255, 255, 255));
        labelRG.setText("RG:");

        campoRG.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoRG.setForeground(new java.awt.Color(153, 153, 153));
        campoRG.setText("X.XXX.XXX");
        campoRG.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoRGFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoRGFocusLost(evt);
            }
        });

        labelDeficiencia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelDeficiencia.setForeground(new java.awt.Color(255, 255, 255));
        labelDeficiencia.setText("Deficiência:");

        campoDeficiencia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoDeficiencia.setForeground(new java.awt.Color(0, 0, 0));

        labelIdLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelIdLogin.setForeground(new java.awt.Color(255, 255, 255));
        labelIdLogin.setText("Código Login:");

        campoIdLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoIdLogin.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanelPessoaLayout = new javax.swing.GroupLayout(jPanelPessoa);
        jPanelPessoa.setLayout(jPanelPessoaLayout);
        jPanelPessoaLayout.setHorizontalGroup(
            jPanelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPessoaLayout.createSequentialGroup()
                .addGroup(jPanelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(labelDeficiencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelTelefone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelCPF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelRG, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(labelIdLogin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoNome)
                    .addComponent(campoCPF)
                    .addComponent(campoTelefone)
                    .addComponent(campoEmail)
                    .addComponent(campoRG)
                    .addComponent(campoDeficiencia)
                    .addComponent(campoIdLogin)))
        );
        jPanelPessoaLayout.setVerticalGroup(
            jPanelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPessoaLayout.createSequentialGroup()
                .addGroup(jPanelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoIdLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelIdLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRG, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDeficiencia, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoDeficiencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        content.add(jPanelPessoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jPanelFormacao.setBackground(new java.awt.Color(19, 16, 89));

        titleFormacao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titleFormacao.setForeground(new java.awt.Color(255, 255, 255));
        titleFormacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleFormacao.setText("Formação");

        campoFormacao.setColumns(20);
        campoFormacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoFormacao.setForeground(new java.awt.Color(0, 0, 0));
        campoFormacao.setLineWrap(true);
        campoFormacao.setRows(5);
        jScrollPane1.setViewportView(campoFormacao);

        javax.swing.GroupLayout jPanelFormacaoLayout = new javax.swing.GroupLayout(jPanelFormacao);
        jPanelFormacao.setLayout(jPanelFormacaoLayout);
        jPanelFormacaoLayout.setHorizontalGroup(
            jPanelFormacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleFormacao, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
            .addGroup(jPanelFormacaoLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanelFormacaoLayout.setVerticalGroup(
            jPanelFormacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormacaoLayout.createSequentialGroup()
                .addComponent(titleFormacao, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
        );

        content.add(jPanelFormacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, 160));

        botaoCadastrar.setBackground(new java.awt.Color(19, 16, 89));
        botaoCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        botaoCadastrar.setText("Cadastrar");
        botaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarActionPerformed(evt);
            }
        });
        content.add(botaoCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 450, -1, -1));

        jPanelCorRaca.setBackground(new java.awt.Color(19, 16, 89));

        botaoBranco.setBackground(new java.awt.Color(19, 16, 89));
        grupoBotoesCorRaca.add(botaoBranco);
        botaoBranco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoBranco.setForeground(new java.awt.Color(255, 255, 255));
        botaoBranco.setText("Branco");

        botaoPardo.setBackground(new java.awt.Color(19, 16, 89));
        grupoBotoesCorRaca.add(botaoPardo);
        botaoPardo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoPardo.setForeground(new java.awt.Color(255, 255, 255));
        botaoPardo.setText("Pardo");

        botaoNegro.setBackground(new java.awt.Color(19, 16, 89));
        grupoBotoesCorRaca.add(botaoNegro);
        botaoNegro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoNegro.setForeground(new java.awt.Color(255, 255, 255));
        botaoNegro.setText("Negro");

        botaoAmarelo.setBackground(new java.awt.Color(19, 16, 89));
        grupoBotoesCorRaca.add(botaoAmarelo);
        botaoAmarelo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoAmarelo.setForeground(new java.awt.Color(255, 255, 255));
        botaoAmarelo.setText("Amarelo");

        botaoIndigena.setBackground(new java.awt.Color(19, 16, 89));
        grupoBotoesCorRaca.add(botaoIndigena);
        botaoIndigena.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoIndigena.setForeground(new java.awt.Color(255, 255, 255));
        botaoIndigena.setText("Indígena");

        titleCorRaca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titleCorRaca.setForeground(new java.awt.Color(255, 255, 255));
        titleCorRaca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleCorRaca.setText("Cor/raça");

        javax.swing.GroupLayout jPanelCorRacaLayout = new javax.swing.GroupLayout(jPanelCorRaca);
        jPanelCorRaca.setLayout(jPanelCorRacaLayout);
        jPanelCorRacaLayout.setHorizontalGroup(
            jPanelCorRacaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botaoBranco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botaoPardo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botaoNegro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botaoAmarelo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botaoIndigena, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
            .addComponent(titleCorRaca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelCorRacaLayout.setVerticalGroup(
            jPanelCorRacaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCorRacaLayout.createSequentialGroup()
                .addComponent(titleCorRaca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoBranco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoPardo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoNegro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoAmarelo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoIndigena)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        content.add(jPanelCorRaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, -1, -1));

        jPanelGenero.setBackground(new java.awt.Color(19, 16, 89));

        botaoMasculino.setBackground(new java.awt.Color(19, 16, 89));
        grupoBotoesGenero.add(botaoMasculino);
        botaoMasculino.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoMasculino.setForeground(new java.awt.Color(255, 255, 255));
        botaoMasculino.setText("Masculino");

        botaoFeminino.setBackground(new java.awt.Color(19, 16, 89));
        grupoBotoesGenero.add(botaoFeminino);
        botaoFeminino.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoFeminino.setForeground(new java.awt.Color(255, 255, 255));
        botaoFeminino.setText("Feminino");

        botaoOutro.setBackground(new java.awt.Color(19, 16, 89));
        grupoBotoesGenero.add(botaoOutro);
        botaoOutro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoOutro.setForeground(new java.awt.Color(255, 255, 255));
        botaoOutro.setText("Outro");

        titleGenero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titleGenero.setForeground(new java.awt.Color(255, 255, 255));
        titleGenero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleGenero.setText("Gênero");

        javax.swing.GroupLayout jPanelGeneroLayout = new javax.swing.GroupLayout(jPanelGenero);
        jPanelGenero.setLayout(jPanelGeneroLayout);
        jPanelGeneroLayout.setHorizontalGroup(
            jPanelGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleGenero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botaoMasculino, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
            .addComponent(botaoFeminino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botaoOutro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelGeneroLayout.setVerticalGroup(
            jPanelGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeneroLayout.createSequentialGroup()
                .addComponent(titleGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoMasculino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoFeminino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoOutro)
                .addContainerGap())
        );

        content.add(jPanelGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 220, -1, -1));

        jPanel1.setBackground(new java.awt.Color(19, 16, 89));

        titleHistoricoProfissional.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titleHistoricoProfissional.setForeground(new java.awt.Color(255, 255, 255));
        titleHistoricoProfissional.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleHistoricoProfissional.setText("Histórico Profissional");

        campoHistoricoProfissional.setColumns(20);
        campoHistoricoProfissional.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoHistoricoProfissional.setForeground(new java.awt.Color(0, 0, 0));
        campoHistoricoProfissional.setRows(5);
        jScrollPane2.setViewportView(campoHistoricoProfissional);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleHistoricoProfissional, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(titleHistoricoProfissional, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
        );

        content.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 340, 160));

        title.setBackground(new java.awt.Color(10, 23, 82));

        titleMain.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        titleMain.setForeground(new java.awt.Color(255, 255, 255));
        titleMain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleMain.setText("Cadastrar Professor");

        javax.swing.GroupLayout titleLayout = new javax.swing.GroupLayout(title);
        title.setLayout(titleLayout);
        titleLayout.setHorizontalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        titleLayout.setVerticalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleMain, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        sidePanel.setBackground(new java.awt.Color(19, 16, 89));

        cadastrarProfessor.setBackground(new java.awt.Color(19, 16, 89));
        cadastrarProfessor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastrarProfessorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cadastrarProfessorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cadastrarProfessorMouseExited(evt);
            }
        });

        icon.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        icon.setForeground(new java.awt.Color(255, 255, 255));
        icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/integrador/escola/images/75px/Adicionar_Cadastro75px.png"))); // NOI18N

        labelSection.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelSection.setForeground(new java.awt.Color(255, 255, 255));
        labelSection.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSection.setText("Cadastrar Professor");

        javax.swing.GroupLayout cadastrarProfessorLayout = new javax.swing.GroupLayout(cadastrarProfessor);
        cadastrarProfessor.setLayout(cadastrarProfessorLayout);
        cadastrarProfessorLayout.setHorizontalGroup(
            cadastrarProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastrarProfessorLayout.createSequentialGroup()
                .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(labelSection, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
        );
        cadastrarProfessorLayout.setVerticalGroup(
            cadastrarProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelSection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        verProfessores.setBackground(new java.awt.Color(19, 16, 89));
        verProfessores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verProfessoresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verProfessoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                verProfessoresMouseExited(evt);
            }
        });

        icon1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        icon1.setForeground(new java.awt.Color(255, 255, 255));
        icon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/integrador/escola/images/75px/ver_cadastros_professor_75px.png"))); // NOI18N

        labelSection1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelSection1.setForeground(new java.awt.Color(255, 255, 255));
        labelSection1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSection1.setText("Ver Professores");

        javax.swing.GroupLayout verProfessoresLayout = new javax.swing.GroupLayout(verProfessores);
        verProfessores.setLayout(verProfessoresLayout);
        verProfessoresLayout.setHorizontalGroup(
            verProfessoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, verProfessoresLayout.createSequentialGroup()
                .addComponent(icon1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(labelSection1, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
        );
        verProfessoresLayout.setVerticalGroup(
            verProfessoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icon1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelSection1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        cadastrarEstudante.setBackground(new java.awt.Color(19, 16, 89));
        cadastrarEstudante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastrarEstudanteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cadastrarEstudanteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cadastrarEstudanteMouseExited(evt);
            }
        });

        iconEstudante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconEstudante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/integrador/escola/images/75px/Adicionar_Cadastro75px.png"))); // NOI18N

        labelSectionEstudante.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelSectionEstudante.setForeground(new java.awt.Color(255, 255, 255));
        labelSectionEstudante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSectionEstudante.setText("Cadastrar Estudante");

        javax.swing.GroupLayout cadastrarEstudanteLayout = new javax.swing.GroupLayout(cadastrarEstudante);
        cadastrarEstudante.setLayout(cadastrarEstudanteLayout);
        cadastrarEstudanteLayout.setHorizontalGroup(
            cadastrarEstudanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastrarEstudanteLayout.createSequentialGroup()
                .addComponent(iconEstudante, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(labelSectionEstudante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cadastrarEstudanteLayout.setVerticalGroup(
            cadastrarEstudanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconEstudante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelSectionEstudante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        verEstudantes.setBackground(new java.awt.Color(19, 16, 89));
        verEstudantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verEstudantesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verEstudantesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                verEstudantesMouseExited(evt);
            }
        });

        icon2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/integrador/escola/images/75px/ver_cadastros_professor_75px.png"))); // NOI18N

        labelVerEstudantes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelVerEstudantes.setForeground(new java.awt.Color(255, 255, 255));
        labelVerEstudantes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelVerEstudantes.setText("Ver Estudantes");

        javax.swing.GroupLayout verEstudantesLayout = new javax.swing.GroupLayout(verEstudantes);
        verEstudantes.setLayout(verEstudantesLayout);
        verEstudantesLayout.setHorizontalGroup(
            verEstudantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verEstudantesLayout.createSequentialGroup()
                .addComponent(icon2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(labelVerEstudantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        verEstudantesLayout.setVerticalGroup(
            verEstudantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icon2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelVerEstudantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(19, 16, 89));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel3MouseExited(evt);
            }
        });

        labelVerEstudantes1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelVerEstudantes1.setForeground(new java.awt.Color(255, 255, 255));
        labelVerEstudantes1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelVerEstudantes1.setText("Cadastrar Login");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/integrador/escola/images/75px/Adicionar_Cadastro75px.png"))); // NOI18N
        jLabel7.setText("jLabel7");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(labelVerEstudantes1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelVerEstudantes1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cadastrarEstudante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(verEstudantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(verProfessores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadastrarProfessor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addComponent(cadastrarProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(verProfessores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(cadastrarEstudante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(verEstudantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 914, Short.MAX_VALUE))
            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                    .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
            
    private void botaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarActionPerformed
        
        ArrayList<AbstractButton> buttonsEstadoCivil = Collections.list(grupoBotoesEstadoCivil.getElements());
        ArrayList<AbstractButton> buttonsCorRaca = Collections.list(grupoBotoesCorRaca.getElements());
        ArrayList<AbstractButton> buttonsGenero = Collections.list(grupoBotoesGenero.getElements());
        
        String nome = campoNome.getText();
        String cpf = campoCPF.getText();
        String rg = campoRG.getText();
        String telefone = campoTelefone.getText();
        String email = campoEmail.getText();
        String deficiencia = campoDeficiencia.getText();
        
        String estado = campoEstado.getText();
        String cidade = campoCidade.getText();
        String bairro = campoBairro.getText();
        int numero;
        try {
            numero = Integer.parseInt(campoNumero.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            return;
        }
        String endereco = campoEndereco.getText();
        String nacionalidade = campoNacionalidade.getText();
        
        int idLogin = Integer.parseInt(campoIdLogin.getText());
        
        
        String formacao = campoFormacao.getText();
        String historicoProfissional = campoHistoricoProfissional.getText();
        String dataNascimentoTexto = campoDataNascimento.getText();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate dataNascimento = LocalDate.parse(dataNascimentoTexto, formatter);
        
        boolean camposInvalidos = 
                nome.isBlank() ||
                cpf.isBlank() ||
                rg.isBlank() ||
                telefone.isBlank() ||
                email.isBlank() ||
                deficiencia.isBlank() ||
                estado.isBlank() ||
                cidade.isBlank() ||
                bairro.isBlank() ||
                numero <= 0 ||
                endereco.isBlank() ||
                historicoProfissional.isBlank();
        try {
            if(camposInvalidos) {
                throw new IllegalArgumentException("Há campos preenchidos incorretamente.");
            }
        } catch(IllegalArgumentException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        System.out.println(telefone);
        int indexEstadoCivil = Manager.getIndexOfButtonSelectByList(buttonsEstadoCivil);
        int indexCorRaca = Manager.getIndexOfButtonSelectByList(buttonsCorRaca);
        int indexGenero = Manager.getIndexOfButtonSelectByList(buttonsGenero);
        
        
        EstadoCivil estadoCivil = EstadoCivil.values()[indexEstadoCivil];
        Endereco ender = new Endereco(estado, cidade, bairro, numero, endereco);
        Genero genero = Genero.values()[indexGenero];
        CorRaca corRaca = CorRaca.values()[indexCorRaca];
        
        Titular titular = new Titular(nome, cpf, rg, telefone, email, nacionalidade, deficiencia, dataNascimento);
        Professor professor = new Professor(titular, ender, estadoCivil, genero, corRaca, formacao, historicoProfissional);
        
        professor.setIdLogin(idLogin);
        
        try {
            SQLManager.cadastrar(professor);
        } catch (SQLException ex) {
            Logger.getLogger(CadastroProfessor.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, "Professor cadastrado.");
    }//GEN-LAST:event_botaoCadastrarActionPerformed
    
   
    private void campoTelefoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoTelefoneFocusGained
        JFrameManager.campoFocusGained(evt, campoTelefone, Placeholder.TELEFONE);
    }//GEN-LAST:event_campoTelefoneFocusGained

    private void campoTelefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoTelefoneFocusLost
        JFrameManager.campoFocusLost(evt, campoTelefone, Placeholder.TELEFONE);
    }//GEN-LAST:event_campoTelefoneFocusLost

    private void campoCPFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCPFFocusGained
        JFrameManager.campoFocusGained(evt, campoCPF, Placeholder.CPF);
    }//GEN-LAST:event_campoCPFFocusGained

    private void campoCPFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCPFFocusLost
        JFrameManager.campoFocusLost(evt, campoCPF, Placeholder.CPF);
    }//GEN-LAST:event_campoCPFFocusLost

    private void campoRGFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoRGFocusGained
        JFrameManager.campoFocusGained(evt, campoRG, Placeholder.RG);
    }//GEN-LAST:event_campoRGFocusGained

    private void campoRGFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoRGFocusLost
        JFrameManager.campoFocusLost(evt, campoRG, Placeholder.RG);
    }//GEN-LAST:event_campoRGFocusLost

    private void campoEstadoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoEstadoFocusGained
        JFrameManager.campoFocusGained(evt, campoEstado, Placeholder.ESTADO);
    }//GEN-LAST:event_campoEstadoFocusGained

    private void campoEstadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoEstadoFocusLost
        JFrameManager.campoFocusLost(evt, campoEstado, Placeholder.ESTADO);
    }//GEN-LAST:event_campoEstadoFocusLost

    private void cadastrarProfessorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarProfessorMouseClicked
        JFrameManager.changeJFrame(evt, new CadastroEstudante());
    }//GEN-LAST:event_cadastrarProfessorMouseClicked

    private void cadastrarProfessorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarProfessorMouseEntered
        JFrameManager.sectionMouseEntered(evt);
    }//GEN-LAST:event_cadastrarProfessorMouseEntered

    private void cadastrarProfessorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarProfessorMouseExited
        JFrameManager.sectionMouseExited(evt);
    }//GEN-LAST:event_cadastrarProfessorMouseExited

    private void verProfessoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verProfessoresMouseClicked
        JFrameManager.changeJFrame(evt, new ProfessoresCadastrados());
    }//GEN-LAST:event_verProfessoresMouseClicked

    private void verProfessoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verProfessoresMouseEntered
        JFrameManager.sectionMouseEntered(evt);
    }//GEN-LAST:event_verProfessoresMouseEntered

    private void verProfessoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verProfessoresMouseExited
        JFrameManager.sectionMouseExited(evt);
    }//GEN-LAST:event_verProfessoresMouseExited

    private void cadastrarEstudanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarEstudanteMouseClicked
        JFrameManager.changeJFrame(evt, new CadastroEstudante());
    }//GEN-LAST:event_cadastrarEstudanteMouseClicked

    private void cadastrarEstudanteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarEstudanteMouseEntered
        JFrameManager.sectionMouseEntered(evt);
    }//GEN-LAST:event_cadastrarEstudanteMouseEntered

    private void cadastrarEstudanteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarEstudanteMouseExited
        JFrameManager.sectionMouseExited(evt);
    }//GEN-LAST:event_cadastrarEstudanteMouseExited

    private void verEstudantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verEstudantesMouseClicked
        JFrameManager.changeJFrame(evt, new EstudantesCadastrados());
    }//GEN-LAST:event_verEstudantesMouseClicked

    private void verEstudantesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verEstudantesMouseEntered
        JFrameManager.sectionMouseEntered(evt);
    }//GEN-LAST:event_verEstudantesMouseEntered

    private void verEstudantesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verEstudantesMouseExited
        JFrameManager.sectionMouseExited(evt);
    }//GEN-LAST:event_verEstudantesMouseExited

    private void campoDataNascimentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoDataNascimentoFocusGained
        JFrameManager.campoFocusGained(evt, campoDataNascimento, Placeholder.DATANASCIMENTO);
    }//GEN-LAST:event_campoDataNascimentoFocusGained

    private void campoDataNascimentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoDataNascimentoFocusLost
        JFrameManager.campoFocusLost(evt, campoDataNascimento, Placeholder.DATANASCIMENTO);
    }//GEN-LAST:event_campoDataNascimentoFocusLost

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        JFrameManager.changeJFrame(evt, new CadastroLogin());
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        JFrameManager.sectionMouseEntered(evt);
    }//GEN-LAST:event_jPanel3MouseEntered

    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseExited
        JFrameManager.sectionMouseExited(evt);
    }//GEN-LAST:event_jPanel3MouseExited
    
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProfessor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JRadioButton botaoAmarelo;
    private javax.swing.JRadioButton botaoBranco;
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JRadioButton botaoCasado;
    private javax.swing.JRadioButton botaoDivorciado;
    private javax.swing.JRadioButton botaoFeminino;
    private javax.swing.JRadioButton botaoIndigena;
    private javax.swing.JRadioButton botaoMasculino;
    private javax.swing.JRadioButton botaoNegro;
    private javax.swing.JRadioButton botaoOutro;
    private javax.swing.JRadioButton botaoPardo;
    private javax.swing.JRadioButton botaoSolteiro;
    private javax.swing.JRadioButton botaoViuvo;
    private javax.swing.JPanel cadastrarEstudante;
    private javax.swing.JPanel cadastrarProfessor;
    private javax.swing.JTextField campoBairro;
    private javax.swing.JTextField campoCPF;
    private javax.swing.JTextField campoCidade;
    private javax.swing.JTextField campoDataNascimento;
    private javax.swing.JTextField campoDeficiencia;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoEndereco;
    private javax.swing.JTextField campoEstado;
    private javax.swing.JTextArea campoFormacao;
    private javax.swing.JTextArea campoHistoricoProfissional;
    private javax.swing.JTextField campoIdLogin;
    private javax.swing.JTextField campoNacionalidade;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoNumero;
    private javax.swing.JTextField campoRG;
    private javax.swing.JTextField campoTelefone;
    private javax.swing.JPanel content;
    private javax.swing.ButtonGroup grupoBotoesCorRaca;
    private javax.swing.ButtonGroup grupoBotoesEstadoCivil;
    private javax.swing.ButtonGroup grupoBotoesGenero;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel icon1;
    private javax.swing.JLabel icon2;
    private javax.swing.JLabel iconEstudante;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelCorRaca;
    private javax.swing.JPanel jPanelEndereco;
    private javax.swing.JPanel jPanelEstadoCivil;
    private javax.swing.JPanel jPanelFormacao;
    private javax.swing.JPanel jPanelGenero;
    private javax.swing.JPanel jPanelPessoa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelBairro;
    private javax.swing.JLabel labelCPF;
    private javax.swing.JLabel labelCidade;
    private javax.swing.JLabel labelCidade1;
    private javax.swing.JLabel labelDataNascimento;
    private javax.swing.JLabel labelDeficiencia;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelEndereco;
    private javax.swing.JLabel labelIdLogin;
    private javax.swing.JLabel labelNacionalidade;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelNumero;
    private javax.swing.JLabel labelRG;
    private javax.swing.JLabel labelSection;
    private javax.swing.JLabel labelSection1;
    private javax.swing.JLabel labelSectionEstudante;
    private javax.swing.JLabel labelTelefone;
    private javax.swing.JLabel labelVerEstudantes;
    private javax.swing.JLabel labelVerEstudantes1;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JPanel title;
    private javax.swing.JLabel titleCorRaca;
    private javax.swing.JLabel titleEstadoCivil;
    private javax.swing.JLabel titleFormacao;
    private javax.swing.JLabel titleGenero;
    private javax.swing.JLabel titleHistoricoProfissional;
    private javax.swing.JLabel titleMain;
    private javax.swing.JPanel verEstudantes;
    private javax.swing.JPanel verProfessores;
    // End of variables declaration//GEN-END:variables
}