package br.com.senac.integrador.escola.modelos.telas;

import br.com.senac.integrador.escola.modelos.Endereco;
import br.com.senac.integrador.escola.modelos.Estudante;
import br.com.senac.integrador.escola.modelos.Titular;
import br.com.senac.integrador.escola.modelos.auxiliares.JFrameManager;
import br.com.senac.integrador.escola.modelos.auxiliares.Manager;
import br.com.senac.integrador.escola.modelos.auxiliares.SQLManager;
import br.com.senac.integrador.escola.modelos.enums.Fator;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * Definição da tela de estudantes cadastrados
 * @author Felipe Godinho Dal Molin
 */
public class EstudantesCadastrados extends javax.swing.JFrame {

    public EstudantesCadastrados() {
        initComponents();
        SQLManager.initConnection();
        try {
            SQLManager.initTableEstudantes(tabelaEstudantes);
        } catch (SQLException ex) {
            Logger.getLogger(EstudantesCadastrados.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        title = new javax.swing.JPanel();
        titleMain = new javax.swing.JLabel();
        sidePanel = new javax.swing.JPanel();
        cadastrarProfessor = new javax.swing.JPanel();
        icon = new javax.swing.JLabel();
        labelSection = new javax.swing.JLabel();
        verProfessores = new javax.swing.JPanel();
        icon1 = new javax.swing.JLabel();
        labelSection1 = new javax.swing.JLabel();
        cadastrarEstudante = new javax.swing.JPanel();
        iconEstudante = new javax.swing.JLabel();
        labelSectionEstudante = new javax.swing.JLabel();
        verEstudantes = new javax.swing.JPanel();
        icon2 = new javax.swing.JLabel();
        labelVerEstudantes = new javax.swing.JLabel();
        cadastrarLogin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        comboBoxPesquisa = new javax.swing.JComboBox<>();
        campoPesquisa = new javax.swing.JTextField();
        labelTituloDescricao = new javax.swing.JLabel();
        botaoObterDescricao = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        campoGenero = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        campoEstadoCivil = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        campoCorRaca = new javax.swing.JTextField();
        labelDeficiencia = new javax.swing.JLabel();
        campoDeficiencia = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        labelEmail = new javax.swing.JLabel();
        campoTelefone = new javax.swing.JTextField();
        campoEmail = new javax.swing.JTextField();
        labelCPF = new javax.swing.JLabel();
        campoCPF = new javax.swing.JTextField();
        labelRG = new javax.swing.JLabel();
        campoRG = new javax.swing.JTextField();
        labelTelefone = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labelID = new javax.swing.JLabel();
        campoID = new javax.swing.JTextField();
        labelNome = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        labelNacionalidade = new javax.swing.JLabel();
        campoNacionalidade = new javax.swing.JTextField();
        campoDataNascimento = new javax.swing.JTextField();
        labelDataNascimento = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        campoNomeResponsavel = new javax.swing.JTextField();
        labelEscolaridade = new javax.swing.JLabel();
        campoEscolaridade = new javax.swing.JTextField();
        labelDataInscricao = new javax.swing.JLabel();
        campoDataInscricao = new javax.swing.JTextField();
        jPanelEndereco = new javax.swing.JPanel();
        campoBairro = new javax.swing.JTextField();
        labelNumero = new javax.swing.JLabel();
        campoNumero = new javax.swing.JTextField();
        labelEndereco = new javax.swing.JLabel();
        campoEndereco = new javax.swing.JTextField();
        labelCidade = new javax.swing.JLabel();
        campoCidade = new javax.swing.JTextField();
        labelCidade1 = new javax.swing.JLabel();
        campoEstado = new javax.swing.JTextField();
        labelBairro = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaEstudantes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Estudantes Cadastrados");

        background.setBackground(new java.awt.Color(255, 255, 255));

        title.setBackground(new java.awt.Color(10, 23, 82));

        titleMain.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        titleMain.setForeground(new java.awt.Color(255, 255, 255));
        titleMain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleMain.setText("Ver Estudantes Cadastrados");

        sidePanel.setBackground(new java.awt.Color(19, 16, 89));

        cadastrarProfessor.setBackground(new java.awt.Color(19, 16, 89));
        cadastrarProfessor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastrarProfessorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cadastrarProfessorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cadastrarProfessorMouseExited(evt);
            }
        });

        icon.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        icon.setForeground(new java.awt.Color(255, 255, 255));
        icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/integrador/escola/images/75px/Adicionar_Cadastro75px.png"))); // NOI18N

        labelSection.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelSection.setForeground(new java.awt.Color(255, 255, 255));
        labelSection.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSection.setText("Cadastrar Professor");

        javax.swing.GroupLayout cadastrarProfessorLayout = new javax.swing.GroupLayout(cadastrarProfessor);
        cadastrarProfessor.setLayout(cadastrarProfessorLayout);
        cadastrarProfessorLayout.setHorizontalGroup(
            cadastrarProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastrarProfessorLayout.createSequentialGroup()
                .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(labelSection, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
        );
        cadastrarProfessorLayout.setVerticalGroup(
            cadastrarProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelSection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        verProfessores.setBackground(new java.awt.Color(19, 16, 89));
        verProfessores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verProfessoresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verProfessoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                verProfessoresMouseExited(evt);
            }
        });

        icon1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        icon1.setForeground(new java.awt.Color(255, 255, 255));
        icon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/integrador/escola/images/75px/ver_cadastros_professor_75px.png"))); // NOI18N

        labelSection1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelSection1.setForeground(new java.awt.Color(255, 255, 255));
        labelSection1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSection1.setText("Ver Professores");

        javax.swing.GroupLayout verProfessoresLayout = new javax.swing.GroupLayout(verProfessores);
        verProfessores.setLayout(verProfessoresLayout);
        verProfessoresLayout.setHorizontalGroup(
            verProfessoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, verProfessoresLayout.createSequentialGroup()
                .addComponent(icon1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(labelSection1, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
        );
        verProfessoresLayout.setVerticalGroup(
            verProfessoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icon1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelSection1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        cadastrarEstudante.setBackground(new java.awt.Color(19, 16, 89));
        cadastrarEstudante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastrarEstudanteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cadastrarEstudanteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cadastrarEstudanteMouseExited(evt);
            }
        });

        iconEstudante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconEstudante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/integrador/escola/images/75px/Adicionar_Cadastro75px.png"))); // NOI18N

        labelSectionEstudante.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelSectionEstudante.setForeground(new java.awt.Color(255, 255, 255));
        labelSectionEstudante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSectionEstudante.setText("Cadastrar Estudante");

        javax.swing.GroupLayout cadastrarEstudanteLayout = new javax.swing.GroupLayout(cadastrarEstudante);
        cadastrarEstudante.setLayout(cadastrarEstudanteLayout);
        cadastrarEstudanteLayout.setHorizontalGroup(
            cadastrarEstudanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastrarEstudanteLayout.createSequentialGroup()
                .addComponent(iconEstudante, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(labelSectionEstudante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cadastrarEstudanteLayout.setVerticalGroup(
            cadastrarEstudanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconEstudante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelSectionEstudante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        verEstudantes.setBackground(new java.awt.Color(19, 16, 89));
        verEstudantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verEstudantesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verEstudantesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                verEstudantesMouseExited(evt);
            }
        });

        icon2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/integrador/escola/images/75px/ver_cadastros_professor_75px.png"))); // NOI18N

        labelVerEstudantes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelVerEstudantes.setForeground(new java.awt.Color(255, 255, 255));
        labelVerEstudantes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelVerEstudantes.setText("Ver Estudantes");

        javax.swing.GroupLayout verEstudantesLayout = new javax.swing.GroupLayout(verEstudantes);
        verEstudantes.setLayout(verEstudantesLayout);
        verEstudantesLayout.setHorizontalGroup(
            verEstudantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verEstudantesLayout.createSequentialGroup()
                .addComponent(icon2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(labelVerEstudantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        verEstudantesLayout.setVerticalGroup(
            verEstudantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icon2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelVerEstudantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        cadastrarLogin.setBackground(new java.awt.Color(19, 16, 89));
        cadastrarLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastrarLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cadastrarLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cadastrarLoginMouseExited(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/integrador/escola/images/75px/Adicionar_Cadastro75px.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cadastrar Login");

        javax.swing.GroupLayout cadastrarLoginLayout = new javax.swing.GroupLayout(cadastrarLogin);
        cadastrarLogin.setLayout(cadastrarLoginLayout);
        cadastrarLoginLayout.setHorizontalGroup(
            cadastrarLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastrarLoginLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        cadastrarLoginLayout.setVerticalGroup(
            cadastrarLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cadastrarEstudante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(verEstudantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(verProfessores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadastrarProfessor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(cadastrarLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addComponent(cadastrarProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(verProfessores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(cadastrarEstudante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(verEstudantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(cadastrarLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        content.setBackground(new java.awt.Color(75, 97, 148));
        content.setAutoscrolls(true);
        content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comboBoxPesquisa.setBackground(new java.awt.Color(10, 23, 82));
        comboBoxPesquisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IDPessoa", "Nome", "Email", "CPF", "RG", "Telefone" }));
        content.add(comboBoxPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 70, 100, 30));
        content.add(campoPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, 120, 30));

        labelTituloDescricao.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelTituloDescricao.setForeground(new java.awt.Color(255, 255, 255));
        labelTituloDescricao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTituloDescricao.setText("Descrição do estudante");
        content.add(labelTituloDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, -1, -1));

        botaoObterDescricao.setBackground(new java.awt.Color(10, 23, 82));
        botaoObterDescricao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoObterDescricao.setForeground(new java.awt.Color(255, 255, 255));
        botaoObterDescricao.setText("Obter descrição");
        botaoObterDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoObterDescricaoActionPerformed(evt);
            }
        });
        content.add(botaoObterDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 170, -1, -1));

        jPanel3.setBackground(new java.awt.Color(10, 23, 82));
        jPanel3.setBorder(null);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Gênero:");

        campoGenero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoGenero.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Estado Civil:");

        campoEstadoCivil.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoEstadoCivil.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cor ou raça:");

        campoCorRaca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoCorRaca.setEnabled(false);

        labelDeficiencia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelDeficiencia.setForeground(new java.awt.Color(255, 255, 255));
        labelDeficiencia.setText("Deficiência:");

        campoDeficiencia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoDeficiencia.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoCorRaca, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(labelDeficiencia, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoDeficiencia, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCorRaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoDeficiencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDeficiencia)))
        );

        content.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 290, -1, -1));

        jPanel4.setBackground(new java.awt.Color(10, 23, 82));
        jPanel4.setBorder(null);

        labelEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelEmail.setForeground(new java.awt.Color(255, 255, 255));
        labelEmail.setText("E-mail:");

        campoTelefone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoTelefone.setEnabled(false);

        campoEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoEmail.setEnabled(false);

        labelCPF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelCPF.setForeground(new java.awt.Color(255, 255, 255));
        labelCPF.setText("CPF:");

        campoCPF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoCPF.setEnabled(false);

        labelRG.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelRG.setForeground(new java.awt.Color(255, 255, 255));
        labelRG.setText("RG:");

        campoRG.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoRG.setEnabled(false);

        labelTelefone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTelefone.setForeground(new java.awt.Color(255, 255, 255));
        labelTelefone.setText("Telefone:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(labelEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(labelCPF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(labelRG, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoRG, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(labelTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCPF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelRG))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTelefone))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        content.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, -1, -1));

        jPanel1.setBackground(new java.awt.Color(10, 23, 82));
        jPanel1.setBorder(null);

        labelID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelID.setForeground(new java.awt.Color(255, 255, 255));
        labelID.setText("ID:");

        campoID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoID.setEnabled(false);

        labelNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNome.setForeground(new java.awt.Color(255, 255, 255));
        labelNome.setText("Nome:");

        campoNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoNome.setEnabled(false);

        labelNacionalidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNacionalidade.setForeground(new java.awt.Color(255, 255, 255));
        labelNacionalidade.setText("Nacionalidade:");

        campoNacionalidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoNacionalidade.setEnabled(false);

        campoDataNascimento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoDataNascimento.setEnabled(false);

        labelDataNascimento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelDataNascimento.setForeground(new java.awt.Color(255, 255, 255));
        labelDataNascimento.setText("Nascimento:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(labelID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoID, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(labelNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(labelNacionalidade, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoNacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(labelDataNascimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNacionalidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDataNascimento)))
        );

        content.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, 150));

        jPanel5.setBackground(new java.awt.Color(10, 23, 82));
        jPanel5.setBorder(null);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nome do responsável:");

        campoNomeResponsavel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoNomeResponsavel.setEnabled(false);

        labelEscolaridade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelEscolaridade.setForeground(new java.awt.Color(255, 255, 255));
        labelEscolaridade.setText("Escolaridade:");

        campoEscolaridade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoEscolaridade.setEnabled(false);

        labelDataInscricao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelDataInscricao.setForeground(new java.awt.Color(255, 255, 255));
        labelDataInscricao.setText("Data de inscrição:");

        campoDataInscricao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoDataInscricao.setEnabled(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoNomeResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(labelEscolaridade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoEscolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(labelDataInscricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoDataInscricao, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNomeResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoEscolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEscolaridade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoDataInscricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDataInscricao))
                .addContainerGap())
        );

        content.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 320, 110));

        jPanelEndereco.setBackground(new java.awt.Color(10, 23, 82));

        campoBairro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoBairro.setForeground(new java.awt.Color(0, 0, 0));
        campoBairro.setEnabled(false);

        labelNumero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNumero.setForeground(new java.awt.Color(255, 255, 255));
        labelNumero.setText("Número:");

        campoNumero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoNumero.setForeground(new java.awt.Color(0, 0, 0));
        campoNumero.setEnabled(false);

        labelEndereco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelEndereco.setForeground(new java.awt.Color(255, 255, 255));
        labelEndereco.setText("Endereço:");

        campoEndereco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoEndereco.setForeground(new java.awt.Color(0, 0, 0));
        campoEndereco.setEnabled(false);

        labelCidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelCidade.setForeground(new java.awt.Color(255, 255, 255));
        labelCidade.setText("Cidade:");

        campoCidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoCidade.setForeground(new java.awt.Color(0, 0, 0));
        campoCidade.setEnabled(false);

        labelCidade1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelCidade1.setForeground(new java.awt.Color(255, 255, 255));
        labelCidade1.setText("Estado:");

        campoEstado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoEstado.setForeground(new java.awt.Color(255, 255, 255));
        campoEstado.setEnabled(false);

        labelBairro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelBairro.setForeground(new java.awt.Color(255, 255, 255));
        labelBairro.setText("Bairro:");

        javax.swing.GroupLayout jPanelEnderecoLayout = new javax.swing.GroupLayout(jPanelEndereco);
        jPanelEndereco.setLayout(jPanelEnderecoLayout);
        jPanelEnderecoLayout.setHorizontalGroup(
            jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                    .addComponent(labelCidade1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(campoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                        .addComponent(labelCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                        .addComponent(labelBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                        .addComponent(labelNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEnderecoLayout.createSequentialGroup()
                .addComponent(labelEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelEnderecoLayout.setVerticalGroup(
            jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCidade1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(campoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        content.add(jPanelEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 460, -1, 180));

        tabelaEstudantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CPF", "RG", "Telefone", "E-mail"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabelaEstudantes);

        content.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 510, 190));

        javax.swing.GroupLayout titleLayout = new javax.swing.GroupLayout(title);
        title.setLayout(titleLayout);
        titleLayout.setHorizontalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(titleLayout.createSequentialGroup()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        titleLayout.setVerticalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleLayout.createSequentialGroup()
                .addComponent(titleMain, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addGroup(titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarProfessorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarProfessorMouseClicked
        JFrameManager.changeJFrame(evt, new CadastroProfessor());
    }//GEN-LAST:event_cadastrarProfessorMouseClicked
    private void cadastrarProfessorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarProfessorMouseEntered
        JFrameManager.sectionMouseEntered(evt);
    }//GEN-LAST:event_cadastrarProfessorMouseEntered
    private void cadastrarProfessorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarProfessorMouseExited
        JFrameManager.sectionMouseExited(evt);
    }//GEN-LAST:event_cadastrarProfessorMouseExited
    private void verProfessoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verProfessoresMouseClicked
        JFrameManager.changeJFrame(evt, new ProfessoresCadastrados());
    }//GEN-LAST:event_verProfessoresMouseClicked
    private void verProfessoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verProfessoresMouseEntered
        JFrameManager.sectionMouseEntered(evt);
    }//GEN-LAST:event_verProfessoresMouseEntered
    private void verProfessoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verProfessoresMouseExited
        JFrameManager.sectionMouseExited(evt);
    }//GEN-LAST:event_verProfessoresMouseExited
    private void cadastrarEstudanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarEstudanteMouseClicked
        JFrameManager.changeJFrame(evt, new CadastroEstudante());
    }//GEN-LAST:event_cadastrarEstudanteMouseClicked
    private void cadastrarEstudanteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarEstudanteMouseEntered
        JFrameManager.sectionMouseEntered(evt);
    }//GEN-LAST:event_cadastrarEstudanteMouseEntered
    private void cadastrarEstudanteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarEstudanteMouseExited
        JFrameManager.sectionMouseExited(evt);
    }//GEN-LAST:event_cadastrarEstudanteMouseExited
    private void verEstudantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verEstudantesMouseClicked
        JFrameManager.changeJFrame(evt, new EstudantesCadastrados());
    }//GEN-LAST:event_verEstudantesMouseClicked
    private void verEstudantesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verEstudantesMouseEntered
        JFrameManager.sectionMouseEntered(evt);
    }//GEN-LAST:event_verEstudantesMouseEntered

    private void verEstudantesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verEstudantesMouseExited
        JFrameManager.sectionMouseExited(evt);
    }//GEN-LAST:event_verEstudantesMouseExited

    private void cadastrarLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarLoginMouseClicked
        JFrameManager.changeJFrame(evt, new CadastroLogin());
    }//GEN-LAST:event_cadastrarLoginMouseClicked

    private void cadastrarLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarLoginMouseEntered
        JFrameManager.sectionMouseEntered(evt);
    }//GEN-LAST:event_cadastrarLoginMouseEntered

    private void cadastrarLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarLoginMouseExited
        JFrameManager.sectionMouseExited(evt);
    }//GEN-LAST:event_cadastrarLoginMouseExited

    private void botaoObterDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoObterDescricaoActionPerformed
        String valor = campoPesquisa.getText();
        String fator = ((String) comboBoxPesquisa.getSelectedItem()).toUpperCase();

        Estudante estudante = null;
        Fator fatora = Fator.valueOf(Fator.class, fator);

        try {
            estudante = SQLManager.buscarEstudante(fatora, valor);
        } catch (Exception ex) { 
            Logger.getLogger(EstudantesCadastrados.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

        setCampos(estudante);
    }//GEN-LAST:event_botaoObterDescricaoActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstudantesCadastrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstudantesCadastrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstudantesCadastrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstudantesCadastrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstudantesCadastrados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton botaoObterDescricao;
    private javax.swing.JPanel cadastrarEstudante;
    private javax.swing.JPanel cadastrarLogin;
    private javax.swing.JPanel cadastrarProfessor;
    private javax.swing.JTextField campoBairro;
    private javax.swing.JTextField campoCPF;
    private javax.swing.JTextField campoCidade;
    private javax.swing.JTextField campoCorRaca;
    private javax.swing.JTextField campoDataInscricao;
    private javax.swing.JTextField campoDataNascimento;
    private javax.swing.JTextField campoDeficiencia;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoEndereco;
    private javax.swing.JTextField campoEscolaridade;
    private javax.swing.JTextField campoEstado;
    private javax.swing.JTextField campoEstadoCivil;
    private javax.swing.JTextField campoGenero;
    private javax.swing.JTextField campoID;
    private javax.swing.JTextField campoNacionalidade;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoNomeResponsavel;
    private javax.swing.JTextField campoNumero;
    private javax.swing.JTextField campoPesquisa;
    private javax.swing.JTextField campoRG;
    private javax.swing.JTextField campoTelefone;
    private javax.swing.JComboBox<String> comboBoxPesquisa;
    private javax.swing.JPanel content;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel icon1;
    private javax.swing.JLabel icon2;
    private javax.swing.JLabel iconEstudante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelEndereco;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelBairro;
    private javax.swing.JLabel labelCPF;
    private javax.swing.JLabel labelCidade;
    private javax.swing.JLabel labelCidade1;
    private javax.swing.JLabel labelDataInscricao;
    private javax.swing.JLabel labelDataNascimento;
    private javax.swing.JLabel labelDeficiencia;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelEndereco;
    private javax.swing.JLabel labelEscolaridade;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel labelNacionalidade;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelNumero;
    private javax.swing.JLabel labelRG;
    private javax.swing.JLabel labelSection;
    private javax.swing.JLabel labelSection1;
    private javax.swing.JLabel labelSectionEstudante;
    private javax.swing.JLabel labelTelefone;
    private javax.swing.JLabel labelTituloDescricao;
    private javax.swing.JLabel labelVerEstudantes;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JTable tabelaEstudantes;
    private javax.swing.JPanel title;
    private javax.swing.JLabel titleMain;
    private javax.swing.JPanel verEstudantes;
    private javax.swing.JPanel verProfessores;
    // End of variables declaration//GEN-END:variables

    private void setCampos(Estudante estudante) {
        Titular titular = estudante.getTitular();
        
        
        campoID.setText(String.valueOf(estudante.getIdPessoa()));
        campoNome.setText(titular.getNome());
        campoCPF.setText(titular.getCPF());
        campoRG.setText(titular.getRG());
        campoEmail.setText(titular.getEmail());
        
        campoTelefone.setText(titular.getTelefone());
        campoNacionalidade.setText(titular.getNacionalidade());
        campoDeficiencia.setText(titular.getDeficiencia());
        
        campoEstadoCivil.setText(estudante.getEstadoCivil().name());
        campoGenero.setText(estudante.getGenero().name());
        campoCorRaca.setText(estudante.getCorRaca().name());
        campoEscolaridade.setText(estudante.getEscolaridade().name());
        
        campoNomeResponsavel.setText(estudante.getNomeResponsavel());
        LocalDate dataNasc = titular.getDataNascimento();
        campoDataNascimento.setText(Manager.formatter.format(dataNasc));
        LocalDate dataInscricao = estudante.getDataInscricao();
        campoDataInscricao.setText(Manager.formatter.format(dataInscricao));
        
        Endereco endereco = estudante.getEndereco();
        campoEstado.setText(endereco.getEstado());
        campoCidade.setText(endereco.getCidade());
        campoBairro.setText(endereco.getBairro());
        campoNumero.setText(String.valueOf(endereco.getNumero()));
        campoEndereco.setText(endereco.getEndereco());
    }
}